// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'adapter.freezed.dart';

class RemoteCapabilities {
  final bool rangeRead;
  final bool pagination;

  const RemoteCapabilities({required this.rangeRead, required this.pagination});

  @override
  int get hashCode => rangeRead.hashCode ^ pagination.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RemoteCapabilities &&
          runtimeType == other.runtimeType &&
          rangeRead == other.rangeRead &&
          pagination == other.pagination;
}

@freezed
sealed class RemoteScanError with _$RemoteScanError implements FrbException {
  const RemoteScanError._();

  const factory RemoteScanError.notFound() = RemoteScanError_NotFound;
  const factory RemoteScanError.forbidden() = RemoteScanError_Forbidden;
  const factory RemoteScanError.rateLimited({BigInt? retryAfterMs}) =
      RemoteScanError_RateLimited;
  const factory RemoteScanError.transientNetwork(String field0) =
      RemoteScanError_TransientNetwork;
  const factory RemoteScanError.malformedResponse(String field0) =
      RemoteScanError_MalformedResponse;
  const factory RemoteScanError.rangeUnavailable() =
      RemoteScanError_RangeUnavailable;
  const factory RemoteScanError.cancelled() = RemoteScanError_Cancelled;
  const factory RemoteScanError.unauthorized() = RemoteScanError_Unauthorized;
  const factory RemoteScanError.unsupported() = RemoteScanError_Unsupported;
  const factory RemoteScanError.io(String field0) = RemoteScanError_Io;
  const factory RemoteScanError.provider(String field0) =
      RemoteScanError_Provider;
}
