// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'model.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class CommittedDirectory {
  final String sourceId;
  final String logicalPath;
  final PlatformInt64 generation;
  final String fingerprint;
  final RemoteAssetKind assetKind;
  final List<RemoteEntry> entries;
  final bool incremental;

  const CommittedDirectory({
    required this.sourceId,
    required this.logicalPath,
    required this.generation,
    required this.fingerprint,
    required this.assetKind,
    required this.entries,
    required this.incremental,
  });

  @override
  int get hashCode =>
      sourceId.hashCode ^
      logicalPath.hashCode ^
      generation.hashCode ^
      fingerprint.hashCode ^
      assetKind.hashCode ^
      entries.hashCode ^
      incremental.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommittedDirectory &&
          runtimeType == other.runtimeType &&
          sourceId == other.sourceId &&
          logicalPath == other.logicalPath &&
          generation == other.generation &&
          fingerprint == other.fingerprint &&
          assetKind == other.assetKind &&
          entries == other.entries &&
          incremental == other.incremental;
}

class CoverTask {
  final String sourceId;
  final String logicalPath;
  final String fingerprint;
  final String profile;

  const CoverTask({
    required this.sourceId,
    required this.logicalPath,
    required this.fingerprint,
    required this.profile,
  });

  @override
  int get hashCode =>
      sourceId.hashCode ^
      logicalPath.hashCode ^
      fingerprint.hashCode ^
      profile.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoverTask &&
          runtimeType == other.runtimeType &&
          sourceId == other.sourceId &&
          logicalPath == other.logicalPath &&
          fingerprint == other.fingerprint &&
          profile == other.profile;
}
