// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

enum RemoteAssetKind {
  archiveFile,
  imageFile,
  imageFolder,
  containerDir,
  plainDir,
  other,
}

class RemoteEntry {
  final String name;
  final String logicalPath;
  final bool isDir;
  final BigInt? size;
  final PlatformInt64? mtime;
  final RemoteAssetKind assetKind;

  const RemoteEntry({
    required this.name,
    required this.logicalPath,
    required this.isDir,
    this.size,
    this.mtime,
    required this.assetKind,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      logicalPath.hashCode ^
      isDir.hashCode ^
      size.hashCode ^
      mtime.hashCode ^
      assetKind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RemoteEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          logicalPath == other.logicalPath &&
          isDir == other.isDir &&
          size == other.size &&
          mtime == other.mtime &&
          assetKind == other.assetKind;
}
