// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/ai.dart';
import 'api/book.dart';
import 'api/cache.dart';
import 'api/db.dart';
import 'api/export.dart';
import 'api/library.dart';
import 'api/package.dart';
import 'api/pdf.dart';
import 'api/scraper.dart';
import 'api/simple.dart';
import 'api/source.dart';
import 'api/sync.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'scrape_projection.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  Map<String, PlatformInt64> dco_decode_Map_String_i_64_None(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AiTaskDto dco_decode_ai_task_dto(dynamic raw);

  @protected
  BaiduSessionInfo dco_decode_baidu_session_info(dynamic raw);

  @protected
  BaiduTokenPair dco_decode_baidu_token_pair(dynamic raw);

  @protected
  BookInfo dco_decode_book_info(dynamic raw);

  @protected
  BookMetaDto dco_decode_book_meta_dto(dynamic raw);

  @protected
  BookSearchDto dco_decode_book_search_dto(dynamic raw);

  @protected
  BookSourceDto dco_decode_book_source_dto(dynamic raw);

  @protected
  BookTagDto dco_decode_book_tag_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AiTaskDto dco_decode_box_autoadd_ai_task_dto(dynamic raw);

  @protected
  BookInfo dco_decode_box_autoadd_book_info(dynamic raw);

  @protected
  BookMetaDto dco_decode_box_autoadd_book_meta_dto(dynamic raw);

  @protected
  BookSourceDto dco_decode_box_autoadd_book_source_dto(dynamic raw);

  @protected
  CatalogRevisionDto dco_decode_box_autoadd_catalog_revision_dto(dynamic raw);

  @protected
  CropRect dco_decode_box_autoadd_crop_rect(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  ReadRecordDto dco_decode_box_autoadd_read_record_dto(dynamic raw);

  @protected
  (String, String) dco_decode_box_autoadd_record_string_string(dynamic raw);

  @protected
  ScrapeQueueDto dco_decode_box_autoadd_scrape_queue_dto(dynamic raw);

  @protected
  SourceSnapshotDto dco_decode_box_autoadd_source_snapshot_dto(dynamic raw);

  @protected
  CacheSize dco_decode_cache_size(dynamic raw);

  @protected
  CatalogRevisionDto dco_decode_catalog_revision_dto(dynamic raw);

  @protected
  Cloud115CookieQrPayload dco_decode_cloud_115_cookie_qr_payload(dynamic raw);

  @protected
  Cloud115CookieSessionInfo dco_decode_cloud_115_cookie_session_info(
    dynamic raw,
  );

  @protected
  Cloud115QrPayload dco_decode_cloud_115_qr_payload(dynamic raw);

  @protected
  Cloud115QrPollResult dco_decode_cloud_115_qr_poll_result(dynamic raw);

  @protected
  Cloud115SessionInfo dco_decode_cloud_115_session_info(dynamic raw);

  @protected
  CropRect dco_decode_crop_rect(dynamic raw);

  @protected
  DeviceDto dco_decode_device_dto(dynamic raw);

  @protected
  DirEntry dco_decode_dir_entry(dynamic raw);

  @protected
  EntityCountDto dco_decode_entity_count_dto(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  IndexEntryInput dco_decode_index_entry_input(dynamic raw);

  @protected
  LibEntryDto dco_decode_lib_entry_dto(dynamic raw);

  @protected
  LibraryIndexDto dco_decode_library_index_dto(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AiTaskDto> dco_decode_list_ai_task_dto(dynamic raw);

  @protected
  List<BookMetaDto> dco_decode_list_book_meta_dto(dynamic raw);

  @protected
  List<BookSearchDto> dco_decode_list_book_search_dto(dynamic raw);

  @protected
  List<BookSourceDto> dco_decode_list_book_source_dto(dynamic raw);

  @protected
  List<BookTagDto> dco_decode_list_book_tag_dto(dynamic raw);

  @protected
  List<DeviceDto> dco_decode_list_device_dto(dynamic raw);

  @protected
  List<DirEntry> dco_decode_list_dir_entry(dynamic raw);

  @protected
  List<EntityCountDto> dco_decode_list_entity_count_dto(dynamic raw);

  @protected
  List<IndexEntryInput> dco_decode_list_index_entry_input(dynamic raw);

  @protected
  List<LibEntryDto> dco_decode_list_lib_entry_dto(dynamic raw);

  @protected
  List<LibraryIndexDto> dco_decode_list_library_index_dto(dynamic raw);

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ReadRecordDto> dco_decode_list_read_record_dto(dynamic raw);

  @protected
  List<(String, PlatformInt64)> dco_decode_list_record_string_i_64(dynamic raw);

  @protected
  List<ScrapeProposalDto> dco_decode_list_scrape_proposal_dto(dynamic raw);

  @protected
  List<ScrapeRunDto> dco_decode_list_scrape_run_dto(dynamic raw);

  @protected
  List<SettingEntryDto> dco_decode_list_setting_entry_dto(dynamic raw);

  @protected
  List<SourceAvailabilityDto> dco_decode_list_source_availability_dto(
    dynamic raw,
  );

  @protected
  List<SourceTreeNodeDto> dco_decode_list_source_tree_node_dto(dynamic raw);

  @protected
  List<SyncDeviceDto> dco_decode_list_sync_device_dto(dynamic raw);

  @protected
  List<SyncHistoryDto> dco_decode_list_sync_history_dto(dynamic raw);

  @protected
  List<TagDto> dco_decode_list_tag_dto(dynamic raw);

  @protected
  MaterializeResult dco_decode_materialize_result(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  BookInfo? dco_decode_opt_box_autoadd_book_info(dynamic raw);

  @protected
  CatalogRevisionDto? dco_decode_opt_box_autoadd_catalog_revision_dto(
    dynamic raw,
  );

  @protected
  CropRect? dco_decode_opt_box_autoadd_crop_rect(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  (String, String)? dco_decode_opt_box_autoadd_record_string_string(
    dynamic raw,
  );

  @protected
  ScrapeQueueDto? dco_decode_opt_box_autoadd_scrape_queue_dto(dynamic raw);

  @protected
  SourceSnapshotDto? dco_decode_opt_box_autoadd_source_snapshot_dto(
    dynamic raw,
  );

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  PageImage dco_decode_page_image(dynamic raw);

  @protected
  QuarkSessionInfo dco_decode_quark_session_info(dynamic raw);

  @protected
  ReadRecordDto dco_decode_read_record_dto(dynamic raw);

  @protected
  (String, PlatformInt64) dco_decode_record_string_i_64(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  (BigInt, BigInt) dco_decode_record_u_64_u_64(dynamic raw);

  @protected
  ScrapeProposalDto dco_decode_scrape_proposal_dto(dynamic raw);

  @protected
  ScrapeQueueDto dco_decode_scrape_queue_dto(dynamic raw);

  @protected
  ScrapeRunDto dco_decode_scrape_run_dto(dynamic raw);

  @protected
  SettingEntryDto dco_decode_setting_entry_dto(dynamic raw);

  @protected
  SftpSessionInfo dco_decode_sftp_session_info(dynamic raw);

  @protected
  SourceAvailabilityDto dco_decode_source_availability_dto(dynamic raw);

  @protected
  SourceSnapshotDto dco_decode_source_snapshot_dto(dynamic raw);

  @protected
  SourceTreeNodeDto dco_decode_source_tree_node_dto(dynamic raw);

  @protected
  SyncDeviceDto dco_decode_sync_device_dto(dynamic raw);

  @protected
  SyncExportInfo dco_decode_sync_export_info(dynamic raw);

  @protected
  SyncHistoryDto dco_decode_sync_history_dto(dynamic raw);

  @protected
  SyncImportStats dco_decode_sync_import_stats(dynamic raw);

  @protected
  SyncOutcomeDto dco_decode_sync_outcome_dto(dynamic raw);

  @protected
  SyncStatusDto dco_decode_sync_status_dto(dynamic raw);

  @protected
  TagDto dco_decode_tag_dto(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  WebDavSession dco_decode_web_dav_session(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  Map<String, PlatformInt64> sse_decode_Map_String_i_64_None(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AiTaskDto sse_decode_ai_task_dto(SseDeserializer deserializer);

  @protected
  BaiduSessionInfo sse_decode_baidu_session_info(SseDeserializer deserializer);

  @protected
  BaiduTokenPair sse_decode_baidu_token_pair(SseDeserializer deserializer);

  @protected
  BookInfo sse_decode_book_info(SseDeserializer deserializer);

  @protected
  BookMetaDto sse_decode_book_meta_dto(SseDeserializer deserializer);

  @protected
  BookSearchDto sse_decode_book_search_dto(SseDeserializer deserializer);

  @protected
  BookSourceDto sse_decode_book_source_dto(SseDeserializer deserializer);

  @protected
  BookTagDto sse_decode_book_tag_dto(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AiTaskDto sse_decode_box_autoadd_ai_task_dto(SseDeserializer deserializer);

  @protected
  BookInfo sse_decode_box_autoadd_book_info(SseDeserializer deserializer);

  @protected
  BookMetaDto sse_decode_box_autoadd_book_meta_dto(
    SseDeserializer deserializer,
  );

  @protected
  BookSourceDto sse_decode_box_autoadd_book_source_dto(
    SseDeserializer deserializer,
  );

  @protected
  CatalogRevisionDto sse_decode_box_autoadd_catalog_revision_dto(
    SseDeserializer deserializer,
  );

  @protected
  CropRect sse_decode_box_autoadd_crop_rect(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  ReadRecordDto sse_decode_box_autoadd_read_record_dto(
    SseDeserializer deserializer,
  );

  @protected
  (String, String) sse_decode_box_autoadd_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  ScrapeQueueDto sse_decode_box_autoadd_scrape_queue_dto(
    SseDeserializer deserializer,
  );

  @protected
  SourceSnapshotDto sse_decode_box_autoadd_source_snapshot_dto(
    SseDeserializer deserializer,
  );

  @protected
  CacheSize sse_decode_cache_size(SseDeserializer deserializer);

  @protected
  CatalogRevisionDto sse_decode_catalog_revision_dto(
    SseDeserializer deserializer,
  );

  @protected
  Cloud115CookieQrPayload sse_decode_cloud_115_cookie_qr_payload(
    SseDeserializer deserializer,
  );

  @protected
  Cloud115CookieSessionInfo sse_decode_cloud_115_cookie_session_info(
    SseDeserializer deserializer,
  );

  @protected
  Cloud115QrPayload sse_decode_cloud_115_qr_payload(
    SseDeserializer deserializer,
  );

  @protected
  Cloud115QrPollResult sse_decode_cloud_115_qr_poll_result(
    SseDeserializer deserializer,
  );

  @protected
  Cloud115SessionInfo sse_decode_cloud_115_session_info(
    SseDeserializer deserializer,
  );

  @protected
  CropRect sse_decode_crop_rect(SseDeserializer deserializer);

  @protected
  DeviceDto sse_decode_device_dto(SseDeserializer deserializer);

  @protected
  DirEntry sse_decode_dir_entry(SseDeserializer deserializer);

  @protected
  EntityCountDto sse_decode_entity_count_dto(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  IndexEntryInput sse_decode_index_entry_input(SseDeserializer deserializer);

  @protected
  LibEntryDto sse_decode_lib_entry_dto(SseDeserializer deserializer);

  @protected
  LibraryIndexDto sse_decode_library_index_dto(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AiTaskDto> sse_decode_list_ai_task_dto(SseDeserializer deserializer);

  @protected
  List<BookMetaDto> sse_decode_list_book_meta_dto(SseDeserializer deserializer);

  @protected
  List<BookSearchDto> sse_decode_list_book_search_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<BookSourceDto> sse_decode_list_book_source_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<BookTagDto> sse_decode_list_book_tag_dto(SseDeserializer deserializer);

  @protected
  List<DeviceDto> sse_decode_list_device_dto(SseDeserializer deserializer);

  @protected
  List<DirEntry> sse_decode_list_dir_entry(SseDeserializer deserializer);

  @protected
  List<EntityCountDto> sse_decode_list_entity_count_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<IndexEntryInput> sse_decode_list_index_entry_input(
    SseDeserializer deserializer,
  );

  @protected
  List<LibEntryDto> sse_decode_list_lib_entry_dto(SseDeserializer deserializer);

  @protected
  List<LibraryIndexDto> sse_decode_list_library_index_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ReadRecordDto> sse_decode_list_read_record_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, PlatformInt64)> sse_decode_list_record_string_i_64(
    SseDeserializer deserializer,
  );

  @protected
  List<ScrapeProposalDto> sse_decode_list_scrape_proposal_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<ScrapeRunDto> sse_decode_list_scrape_run_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<SettingEntryDto> sse_decode_list_setting_entry_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<SourceAvailabilityDto> sse_decode_list_source_availability_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<SourceTreeNodeDto> sse_decode_list_source_tree_node_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<SyncDeviceDto> sse_decode_list_sync_device_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<SyncHistoryDto> sse_decode_list_sync_history_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<TagDto> sse_decode_list_tag_dto(SseDeserializer deserializer);

  @protected
  MaterializeResult sse_decode_materialize_result(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  BookInfo? sse_decode_opt_box_autoadd_book_info(SseDeserializer deserializer);

  @protected
  CatalogRevisionDto? sse_decode_opt_box_autoadd_catalog_revision_dto(
    SseDeserializer deserializer,
  );

  @protected
  CropRect? sse_decode_opt_box_autoadd_crop_rect(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  (String, String)? sse_decode_opt_box_autoadd_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  ScrapeQueueDto? sse_decode_opt_box_autoadd_scrape_queue_dto(
    SseDeserializer deserializer,
  );

  @protected
  SourceSnapshotDto? sse_decode_opt_box_autoadd_source_snapshot_dto(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  PageImage sse_decode_page_image(SseDeserializer deserializer);

  @protected
  QuarkSessionInfo sse_decode_quark_session_info(SseDeserializer deserializer);

  @protected
  ReadRecordDto sse_decode_read_record_dto(SseDeserializer deserializer);

  @protected
  (String, PlatformInt64) sse_decode_record_string_i_64(
    SseDeserializer deserializer,
  );

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  (BigInt, BigInt) sse_decode_record_u_64_u_64(SseDeserializer deserializer);

  @protected
  ScrapeProposalDto sse_decode_scrape_proposal_dto(
    SseDeserializer deserializer,
  );

  @protected
  ScrapeQueueDto sse_decode_scrape_queue_dto(SseDeserializer deserializer);

  @protected
  ScrapeRunDto sse_decode_scrape_run_dto(SseDeserializer deserializer);

  @protected
  SettingEntryDto sse_decode_setting_entry_dto(SseDeserializer deserializer);

  @protected
  SftpSessionInfo sse_decode_sftp_session_info(SseDeserializer deserializer);

  @protected
  SourceAvailabilityDto sse_decode_source_availability_dto(
    SseDeserializer deserializer,
  );

  @protected
  SourceSnapshotDto sse_decode_source_snapshot_dto(
    SseDeserializer deserializer,
  );

  @protected
  SourceTreeNodeDto sse_decode_source_tree_node_dto(
    SseDeserializer deserializer,
  );

  @protected
  SyncDeviceDto sse_decode_sync_device_dto(SseDeserializer deserializer);

  @protected
  SyncExportInfo sse_decode_sync_export_info(SseDeserializer deserializer);

  @protected
  SyncHistoryDto sse_decode_sync_history_dto(SseDeserializer deserializer);

  @protected
  SyncImportStats sse_decode_sync_import_stats(SseDeserializer deserializer);

  @protected
  SyncOutcomeDto sse_decode_sync_outcome_dto(SseDeserializer deserializer);

  @protected
  SyncStatusDto sse_decode_sync_status_dto(SseDeserializer deserializer);

  @protected
  TagDto sse_decode_tag_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  WebDavSession sse_decode_web_dav_session(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_i_64_None(
    Map<String, PlatformInt64> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_ai_task_dto(AiTaskDto self, SseSerializer serializer);

  @protected
  void sse_encode_baidu_session_info(
    BaiduSessionInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_baidu_token_pair(
    BaiduTokenPair self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_book_info(BookInfo self, SseSerializer serializer);

  @protected
  void sse_encode_book_meta_dto(BookMetaDto self, SseSerializer serializer);

  @protected
  void sse_encode_book_search_dto(BookSearchDto self, SseSerializer serializer);

  @protected
  void sse_encode_book_source_dto(BookSourceDto self, SseSerializer serializer);

  @protected
  void sse_encode_book_tag_dto(BookTagDto self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ai_task_dto(
    AiTaskDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_book_info(
    BookInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_book_meta_dto(
    BookMetaDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_book_source_dto(
    BookSourceDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_catalog_revision_dto(
    CatalogRevisionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_crop_rect(
    CropRect self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_read_record_dto(
    ReadRecordDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_scrape_queue_dto(
    ScrapeQueueDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_source_snapshot_dto(
    SourceSnapshotDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_cache_size(CacheSize self, SseSerializer serializer);

  @protected
  void sse_encode_catalog_revision_dto(
    CatalogRevisionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_cloud_115_cookie_qr_payload(
    Cloud115CookieQrPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_cloud_115_cookie_session_info(
    Cloud115CookieSessionInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_cloud_115_qr_payload(
    Cloud115QrPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_cloud_115_qr_poll_result(
    Cloud115QrPollResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_cloud_115_session_info(
    Cloud115SessionInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_crop_rect(CropRect self, SseSerializer serializer);

  @protected
  void sse_encode_device_dto(DeviceDto self, SseSerializer serializer);

  @protected
  void sse_encode_dir_entry(DirEntry self, SseSerializer serializer);

  @protected
  void sse_encode_entity_count_dto(
    EntityCountDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_index_entry_input(
    IndexEntryInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_lib_entry_dto(LibEntryDto self, SseSerializer serializer);

  @protected
  void sse_encode_library_index_dto(
    LibraryIndexDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ai_task_dto(
    List<AiTaskDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_book_meta_dto(
    List<BookMetaDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_book_search_dto(
    List<BookSearchDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_book_source_dto(
    List<BookSourceDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_book_tag_dto(
    List<BookTagDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_device_dto(
    List<DeviceDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_dir_entry(List<DirEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_entity_count_dto(
    List<EntityCountDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_index_entry_input(
    List<IndexEntryInput> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_lib_entry_dto(
    List<LibEntryDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_library_index_dto(
    List<LibraryIndexDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_list_prim_u_8_strict(
    List<Uint8List> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_read_record_dto(
    List<ReadRecordDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_i_64(
    List<(String, PlatformInt64)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_scrape_proposal_dto(
    List<ScrapeProposalDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_scrape_run_dto(
    List<ScrapeRunDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_setting_entry_dto(
    List<SettingEntryDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_source_availability_dto(
    List<SourceAvailabilityDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_source_tree_node_dto(
    List<SourceTreeNodeDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_sync_device_dto(
    List<SyncDeviceDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_sync_history_dto(
    List<SyncHistoryDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_tag_dto(List<TagDto> self, SseSerializer serializer);

  @protected
  void sse_encode_materialize_result(
    MaterializeResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_book_info(
    BookInfo? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_catalog_revision_dto(
    CatalogRevisionDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_crop_rect(
    CropRect? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_record_string_string(
    (String, String)? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_scrape_queue_dto(
    ScrapeQueueDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_source_snapshot_dto(
    SourceSnapshotDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_page_image(PageImage self, SseSerializer serializer);

  @protected
  void sse_encode_quark_session_info(
    QuarkSessionInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_read_record_dto(ReadRecordDto self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_i_64(
    (String, PlatformInt64) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_u_64_u_64(
    (BigInt, BigInt) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_scrape_proposal_dto(
    ScrapeProposalDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_scrape_queue_dto(
    ScrapeQueueDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_scrape_run_dto(ScrapeRunDto self, SseSerializer serializer);

  @protected
  void sse_encode_setting_entry_dto(
    SettingEntryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sftp_session_info(
    SftpSessionInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_source_availability_dto(
    SourceAvailabilityDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_source_snapshot_dto(
    SourceSnapshotDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_source_tree_node_dto(
    SourceTreeNodeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sync_device_dto(SyncDeviceDto self, SseSerializer serializer);

  @protected
  void sse_encode_sync_export_info(
    SyncExportInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sync_history_dto(
    SyncHistoryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sync_import_stats(
    SyncImportStats self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sync_outcome_dto(
    SyncOutcomeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sync_status_dto(SyncStatusDto self, SseSerializer serializer);

  @protected
  void sse_encode_tag_dto(TagDto self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_web_dav_session(WebDavSession self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
