// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/ai.dart';
import 'api/book.dart';
import 'api/cache.dart';
import 'api/db.dart';
import 'api/export.dart';
import 'api/simple.dart';
import 'api/source.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AiTaskDto dco_decode_ai_task_dto(dynamic raw);

  @protected
  BookInfo dco_decode_book_info(dynamic raw);

  @protected
  BookMetaDto dco_decode_book_meta_dto(dynamic raw);

  @protected
  BookSourceDto dco_decode_book_source_dto(dynamic raw);

  @protected
  BookTagDto dco_decode_book_tag_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AiTaskDto dco_decode_box_autoadd_ai_task_dto(dynamic raw);

  @protected
  BookMetaDto dco_decode_box_autoadd_book_meta_dto(dynamic raw);

  @protected
  BookSourceDto dco_decode_box_autoadd_book_source_dto(dynamic raw);

  @protected
  CropRect dco_decode_box_autoadd_crop_rect(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  ReadRecordDto dco_decode_box_autoadd_read_record_dto(dynamic raw);

  @protected
  (String, String) dco_decode_box_autoadd_record_string_string(dynamic raw);

  @protected
  CacheSize dco_decode_cache_size(dynamic raw);

  @protected
  CropRect dco_decode_crop_rect(dynamic raw);

  @protected
  DirEntry dco_decode_dir_entry(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AiTaskDto> dco_decode_list_ai_task_dto(dynamic raw);

  @protected
  List<BookMetaDto> dco_decode_list_book_meta_dto(dynamic raw);

  @protected
  List<BookSourceDto> dco_decode_list_book_source_dto(dynamic raw);

  @protected
  List<BookTagDto> dco_decode_list_book_tag_dto(dynamic raw);

  @protected
  List<DirEntry> dco_decode_list_dir_entry(dynamic raw);

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ReadRecordDto> dco_decode_list_read_record_dto(dynamic raw);

  @protected
  List<SettingEntryDto> dco_decode_list_setting_entry_dto(dynamic raw);

  @protected
  List<TagDto> dco_decode_list_tag_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  CropRect? dco_decode_opt_box_autoadd_crop_rect(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  (String, String)? dco_decode_opt_box_autoadd_record_string_string(
    dynamic raw,
  );

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  PageImage dco_decode_page_image(dynamic raw);

  @protected
  ReadRecordDto dco_decode_read_record_dto(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  (BigInt, BigInt) dco_decode_record_u_64_u_64(dynamic raw);

  @protected
  SettingEntryDto dco_decode_setting_entry_dto(dynamic raw);

  @protected
  TagDto dco_decode_tag_dto(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  WebDavSession dco_decode_web_dav_session(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AiTaskDto sse_decode_ai_task_dto(SseDeserializer deserializer);

  @protected
  BookInfo sse_decode_book_info(SseDeserializer deserializer);

  @protected
  BookMetaDto sse_decode_book_meta_dto(SseDeserializer deserializer);

  @protected
  BookSourceDto sse_decode_book_source_dto(SseDeserializer deserializer);

  @protected
  BookTagDto sse_decode_book_tag_dto(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AiTaskDto sse_decode_box_autoadd_ai_task_dto(SseDeserializer deserializer);

  @protected
  BookMetaDto sse_decode_box_autoadd_book_meta_dto(
    SseDeserializer deserializer,
  );

  @protected
  BookSourceDto sse_decode_box_autoadd_book_source_dto(
    SseDeserializer deserializer,
  );

  @protected
  CropRect sse_decode_box_autoadd_crop_rect(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  ReadRecordDto sse_decode_box_autoadd_read_record_dto(
    SseDeserializer deserializer,
  );

  @protected
  (String, String) sse_decode_box_autoadd_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  CacheSize sse_decode_cache_size(SseDeserializer deserializer);

  @protected
  CropRect sse_decode_crop_rect(SseDeserializer deserializer);

  @protected
  DirEntry sse_decode_dir_entry(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AiTaskDto> sse_decode_list_ai_task_dto(SseDeserializer deserializer);

  @protected
  List<BookMetaDto> sse_decode_list_book_meta_dto(SseDeserializer deserializer);

  @protected
  List<BookSourceDto> sse_decode_list_book_source_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<BookTagDto> sse_decode_list_book_tag_dto(SseDeserializer deserializer);

  @protected
  List<DirEntry> sse_decode_list_dir_entry(SseDeserializer deserializer);

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ReadRecordDto> sse_decode_list_read_record_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<SettingEntryDto> sse_decode_list_setting_entry_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<TagDto> sse_decode_list_tag_dto(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  CropRect? sse_decode_opt_box_autoadd_crop_rect(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  (String, String)? sse_decode_opt_box_autoadd_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  PageImage sse_decode_page_image(SseDeserializer deserializer);

  @protected
  ReadRecordDto sse_decode_read_record_dto(SseDeserializer deserializer);

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  (BigInt, BigInt) sse_decode_record_u_64_u_64(SseDeserializer deserializer);

  @protected
  SettingEntryDto sse_decode_setting_entry_dto(SseDeserializer deserializer);

  @protected
  TagDto sse_decode_tag_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  WebDavSession sse_decode_web_dav_session(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_ai_task_dto(AiTaskDto self, SseSerializer serializer);

  @protected
  void sse_encode_book_info(BookInfo self, SseSerializer serializer);

  @protected
  void sse_encode_book_meta_dto(BookMetaDto self, SseSerializer serializer);

  @protected
  void sse_encode_book_source_dto(BookSourceDto self, SseSerializer serializer);

  @protected
  void sse_encode_book_tag_dto(BookTagDto self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ai_task_dto(
    AiTaskDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_book_meta_dto(
    BookMetaDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_book_source_dto(
    BookSourceDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_crop_rect(
    CropRect self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_read_record_dto(
    ReadRecordDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_cache_size(CacheSize self, SseSerializer serializer);

  @protected
  void sse_encode_crop_rect(CropRect self, SseSerializer serializer);

  @protected
  void sse_encode_dir_entry(DirEntry self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ai_task_dto(
    List<AiTaskDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_book_meta_dto(
    List<BookMetaDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_book_source_dto(
    List<BookSourceDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_book_tag_dto(
    List<BookTagDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_dir_entry(List<DirEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_list_prim_u_8_strict(
    List<Uint8List> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_read_record_dto(
    List<ReadRecordDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_setting_entry_dto(
    List<SettingEntryDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_tag_dto(List<TagDto> self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_crop_rect(
    CropRect? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_record_string_string(
    (String, String)? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_page_image(PageImage self, SseSerializer serializer);

  @protected
  void sse_encode_read_record_dto(ReadRecordDto self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_u_64_u_64(
    (BigInt, BigInt) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_setting_entry_dto(
    SettingEntryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_tag_dto(TagDto self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_web_dav_session(WebDavSession self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
