// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/book.dart';
import 'api/cache.dart';
import 'api/simple.dart';
import 'api/source.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1253216115;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_app',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<PageImage> crateApiBookBookCover({
    required String path,
    required int page,
    required int width,
    required int height,
    CropRect? crop,
  });

  Future<Uint8List> crateApiBookBookPage({
    required BigInt handle,
    required int index,
  });

  Future<String> crateApiCacheCacheRootPath();

  Future<CacheSize> crateApiCacheCacheSizes();

  Future<BigInt> crateApiCacheClearAiCache();

  Future<BigInt> crateApiCacheClearAllCaches();

  Future<BigInt> crateApiCacheClearCoverCache();

  Future<BigInt> crateApiCacheClearDownloadCache();

  Future<BigInt> crateApiCacheClearPageCache();

  Future<BigInt> crateApiCacheClearRawCache();

  Future<BigInt> crateApiCacheClearTempCache();

  Future<BigInt> crateApiCacheClearThumbCache();

  Future<void> crateApiBookCloseBook({required BigInt handle});

  Future<String> crateApiCacheDefaultCacheRootPath();

  Future<BigInt> crateApiCacheDownloadCacheSize();

  Future<String> crateApiBookFolderCoverPath({required String dirPath});

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  Future<bool> crateApiBookIsComicFolder({required String dirPath});

  Future<List<DirEntry>> crateApiBookListLocalDir({required String path});

  Future<BookInfo> crateApiBookOpenLocalBook({required String path});

  Future<BookInfo> crateApiSourceOpenWebdavBook({
    required BigInt session,
    required String path,
  });

  Future<BigInt> crateApiCachePageCacheSize();

  Future<void> crateApiCacheSetCacheRootPath({required String path});

  Future<BigInt> crateApiCacheTotalCacheSize();

  Future<WebDavSession> crateApiSourceWebdavConnect({
    required String url,
    required String username,
    required String password,
  });

  Future<PageImage> crateApiSourceWebdavCover({
    required BigInt session,
    required String path,
    required int page,
    required int width,
    required int height,
    CropRect? crop,
  });

  Future<void> crateApiSourceWebdavDisconnect({required BigInt id});

  Future<double> crateApiSourceWebdavDownloadProgress({
    required BigInt session,
  });

  Future<bool> crateApiSourceWebdavHasRawCache({
    required BigInt session,
    required String path,
  });

  Future<List<DirEntry>> crateApiSourceWebdavList({
    required BigInt session,
    required String path,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<PageImage> crateApiBookBookCover({
    required String path,
    required int page,
    required int width,
    required int height,
    CropRect? crop,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_u_32(page, serializer);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          sse_encode_opt_box_autoadd_crop_rect(crop, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_page_image,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBookBookCoverConstMeta,
        argValues: [path, page, width, height, crop],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBookBookCoverConstMeta => const TaskConstMeta(
    debugName: "book_cover",
    argNames: ["path", "page", "width", "height", "crop"],
  );

  @override
  Future<Uint8List> crateApiBookBookPage({
    required BigInt handle,
    required int index,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handle, serializer);
          sse_encode_u_32(index, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBookBookPageConstMeta,
        argValues: [handle, index],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBookBookPageConstMeta => const TaskConstMeta(
    debugName: "book_page",
    argNames: ["handle", "index"],
  );

  @override
  Future<String> crateApiCacheCacheRootPath() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCacheCacheRootPathConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCacheCacheRootPathConstMeta =>
      const TaskConstMeta(debugName: "cache_root_path", argNames: []);

  @override
  Future<CacheSize> crateApiCacheCacheSizes() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_cache_size,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCacheCacheSizesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCacheCacheSizesConstMeta =>
      const TaskConstMeta(debugName: "cache_sizes", argNames: []);

  @override
  Future<BigInt> crateApiCacheClearAiCache() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCacheClearAiCacheConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCacheClearAiCacheConstMeta =>
      const TaskConstMeta(debugName: "clear_ai_cache", argNames: []);

  @override
  Future<BigInt> crateApiCacheClearAllCaches() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCacheClearAllCachesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCacheClearAllCachesConstMeta =>
      const TaskConstMeta(debugName: "clear_all_caches", argNames: []);

  @override
  Future<BigInt> crateApiCacheClearCoverCache() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCacheClearCoverCacheConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCacheClearCoverCacheConstMeta =>
      const TaskConstMeta(debugName: "clear_cover_cache", argNames: []);

  @override
  Future<BigInt> crateApiCacheClearDownloadCache() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCacheClearDownloadCacheConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCacheClearDownloadCacheConstMeta =>
      const TaskConstMeta(debugName: "clear_download_cache", argNames: []);

  @override
  Future<BigInt> crateApiCacheClearPageCache() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCacheClearPageCacheConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCacheClearPageCacheConstMeta =>
      const TaskConstMeta(debugName: "clear_page_cache", argNames: []);

  @override
  Future<BigInt> crateApiCacheClearRawCache() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCacheClearRawCacheConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCacheClearRawCacheConstMeta =>
      const TaskConstMeta(debugName: "clear_raw_cache", argNames: []);

  @override
  Future<BigInt> crateApiCacheClearTempCache() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCacheClearTempCacheConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCacheClearTempCacheConstMeta =>
      const TaskConstMeta(debugName: "clear_temp_cache", argNames: []);

  @override
  Future<BigInt> crateApiCacheClearThumbCache() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCacheClearThumbCacheConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCacheClearThumbCacheConstMeta =>
      const TaskConstMeta(debugName: "clear_thumb_cache", argNames: []);

  @override
  Future<void> crateApiBookCloseBook({required BigInt handle}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handle, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBookCloseBookConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBookCloseBookConstMeta =>
      const TaskConstMeta(debugName: "close_book", argNames: ["handle"]);

  @override
  Future<String> crateApiCacheDefaultCacheRootPath() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCacheDefaultCacheRootPathConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCacheDefaultCacheRootPathConstMeta =>
      const TaskConstMeta(debugName: "default_cache_root_path", argNames: []);

  @override
  Future<BigInt> crateApiCacheDownloadCacheSize() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCacheDownloadCacheSizeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCacheDownloadCacheSizeConstMeta =>
      const TaskConstMeta(debugName: "download_cache_size", argNames: []);

  @override
  Future<String> crateApiBookFolderCoverPath({required String dirPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dirPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBookFolderCoverPathConstMeta,
        argValues: [dirPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBookFolderCoverPathConstMeta =>
      const TaskConstMeta(
        debugName: "folder_cover_path",
        argNames: ["dirPath"],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<bool> crateApiBookIsComicFolder({required String dirPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dirPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBookIsComicFolderConstMeta,
        argValues: [dirPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBookIsComicFolderConstMeta =>
      const TaskConstMeta(debugName: "is_comic_folder", argNames: ["dirPath"]);

  @override
  Future<List<DirEntry>> crateApiBookListLocalDir({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_dir_entry,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBookListLocalDirConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBookListLocalDirConstMeta =>
      const TaskConstMeta(debugName: "list_local_dir", argNames: ["path"]);

  @override
  Future<BookInfo> crateApiBookOpenLocalBook({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_book_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBookOpenLocalBookConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBookOpenLocalBookConstMeta =>
      const TaskConstMeta(debugName: "open_local_book", argNames: ["path"]);

  @override
  Future<BookInfo> crateApiSourceOpenWebdavBook({
    required BigInt session,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(session, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_book_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSourceOpenWebdavBookConstMeta,
        argValues: [session, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSourceOpenWebdavBookConstMeta =>
      const TaskConstMeta(
        debugName: "open_webdav_book",
        argNames: ["session", "path"],
      );

  @override
  Future<BigInt> crateApiCachePageCacheSize() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCachePageCacheSizeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCachePageCacheSizeConstMeta =>
      const TaskConstMeta(debugName: "page_cache_size", argNames: []);

  @override
  Future<void> crateApiCacheSetCacheRootPath({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCacheSetCacheRootPathConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCacheSetCacheRootPathConstMeta =>
      const TaskConstMeta(debugName: "set_cache_root_path", argNames: ["path"]);

  @override
  Future<BigInt> crateApiCacheTotalCacheSize() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCacheTotalCacheSizeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCacheTotalCacheSizeConstMeta =>
      const TaskConstMeta(debugName: "total_cache_size", argNames: []);

  @override
  Future<WebDavSession> crateApiSourceWebdavConnect({
    required String url,
    required String username,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          sse_encode_String(username, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_web_dav_session,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSourceWebdavConnectConstMeta,
        argValues: [url, username, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSourceWebdavConnectConstMeta =>
      const TaskConstMeta(
        debugName: "webdav_connect",
        argNames: ["url", "username", "password"],
      );

  @override
  Future<PageImage> crateApiSourceWebdavCover({
    required BigInt session,
    required String path,
    required int page,
    required int width,
    required int height,
    CropRect? crop,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(session, serializer);
          sse_encode_String(path, serializer);
          sse_encode_u_32(page, serializer);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          sse_encode_opt_box_autoadd_crop_rect(crop, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_page_image,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSourceWebdavCoverConstMeta,
        argValues: [session, path, page, width, height, crop],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSourceWebdavCoverConstMeta => const TaskConstMeta(
    debugName: "webdav_cover",
    argNames: ["session", "path", "page", "width", "height", "crop"],
  );

  @override
  Future<void> crateApiSourceWebdavDisconnect({required BigInt id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSourceWebdavDisconnectConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSourceWebdavDisconnectConstMeta =>
      const TaskConstMeta(debugName: "webdav_disconnect", argNames: ["id"]);

  @override
  Future<double> crateApiSourceWebdavDownloadProgress({
    required BigInt session,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(session, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSourceWebdavDownloadProgressConstMeta,
        argValues: [session],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSourceWebdavDownloadProgressConstMeta =>
      const TaskConstMeta(
        debugName: "webdav_download_progress",
        argNames: ["session"],
      );

  @override
  Future<bool> crateApiSourceWebdavHasRawCache({
    required BigInt session,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(session, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSourceWebdavHasRawCacheConstMeta,
        argValues: [session, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSourceWebdavHasRawCacheConstMeta =>
      const TaskConstMeta(
        debugName: "webdav_has_raw_cache",
        argNames: ["session", "path"],
      );

  @override
  Future<List<DirEntry>> crateApiSourceWebdavList({
    required BigInt session,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(session, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_dir_entry,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSourceWebdavListConstMeta,
        argValues: [session, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSourceWebdavListConstMeta => const TaskConstMeta(
    debugName: "webdav_list",
    argNames: ["session", "path"],
  );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  BookInfo dco_decode_book_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return BookInfo(
      handle: dco_decode_u_64(arr[0]),
      title: dco_decode_String(arr[1]),
      pageCount: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  CropRect dco_decode_box_autoadd_crop_rect(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_crop_rect(raw);
  }

  @protected
  CacheSize dco_decode_cache_size(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return CacheSize(
      page: dco_decode_u_64(arr[0]),
      raw: dco_decode_u_64(arr[1]),
      cover: dco_decode_u_64(arr[2]),
      thumb: dco_decode_u_64(arr[3]),
      ai: dco_decode_u_64(arr[4]),
      download: dco_decode_u_64(arr[5]),
      temp: dco_decode_u_64(arr[6]),
      total: dco_decode_u_64(arr[7]),
    );
  }

  @protected
  CropRect dco_decode_crop_rect(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return CropRect(
      x: dco_decode_f_64(arr[0]),
      y: dco_decode_f_64(arr[1]),
      w: dco_decode_f_64(arr[2]),
      h: dco_decode_f_64(arr[3]),
    );
  }

  @protected
  DirEntry dco_decode_dir_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return DirEntry(
      name: dco_decode_String(arr[0]),
      path: dco_decode_String(arr[1]),
      isDir: dco_decode_bool(arr[2]),
      size: dco_decode_u_64(arr[3]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  List<DirEntry> dco_decode_list_dir_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_dir_entry).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  CropRect? dco_decode_opt_box_autoadd_crop_rect(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_crop_rect(raw);
  }

  @protected
  PageImage dco_decode_page_image(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return PageImage(
      rgba: dco_decode_list_prim_u_8_strict(arr[0]),
      width: dco_decode_u_32(arr[1]),
      height: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  WebDavSession dco_decode_web_dav_session(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return WebDavSession(
      id: dco_decode_u_64(arr[0]),
      root: dco_decode_String(arr[1]),
      capabilityLabel: dco_decode_String(arr[2]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BookInfo sse_decode_book_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_handle = sse_decode_u_64(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_pageCount = sse_decode_u_32(deserializer);
    return BookInfo(
      handle: var_handle,
      title: var_title,
      pageCount: var_pageCount,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  CropRect sse_decode_box_autoadd_crop_rect(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_crop_rect(deserializer));
  }

  @protected
  CacheSize sse_decode_cache_size(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_page = sse_decode_u_64(deserializer);
    var var_raw = sse_decode_u_64(deserializer);
    var var_cover = sse_decode_u_64(deserializer);
    var var_thumb = sse_decode_u_64(deserializer);
    var var_ai = sse_decode_u_64(deserializer);
    var var_download = sse_decode_u_64(deserializer);
    var var_temp = sse_decode_u_64(deserializer);
    var var_total = sse_decode_u_64(deserializer);
    return CacheSize(
      page: var_page,
      raw: var_raw,
      cover: var_cover,
      thumb: var_thumb,
      ai: var_ai,
      download: var_download,
      temp: var_temp,
      total: var_total,
    );
  }

  @protected
  CropRect sse_decode_crop_rect(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_x = sse_decode_f_64(deserializer);
    var var_y = sse_decode_f_64(deserializer);
    var var_w = sse_decode_f_64(deserializer);
    var var_h = sse_decode_f_64(deserializer);
    return CropRect(x: var_x, y: var_y, w: var_w, h: var_h);
  }

  @protected
  DirEntry sse_decode_dir_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_isDir = sse_decode_bool(deserializer);
    var var_size = sse_decode_u_64(deserializer);
    return DirEntry(
      name: var_name,
      path: var_path,
      isDir: var_isDir,
      size: var_size,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  List<DirEntry> sse_decode_list_dir_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DirEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_dir_entry(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  CropRect? sse_decode_opt_box_autoadd_crop_rect(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_crop_rect(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PageImage sse_decode_page_image(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_rgba = sse_decode_list_prim_u_8_strict(deserializer);
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    return PageImage(rgba: var_rgba, width: var_width, height: var_height);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  WebDavSession sse_decode_web_dav_session(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_u_64(deserializer);
    var var_root = sse_decode_String(deserializer);
    var var_capabilityLabel = sse_decode_String(deserializer);
    return WebDavSession(
      id: var_id,
      root: var_root,
      capabilityLabel: var_capabilityLabel,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_book_info(BookInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.handle, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_u_32(self.pageCount, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_crop_rect(
    CropRect self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_crop_rect(self, serializer);
  }

  @protected
  void sse_encode_cache_size(CacheSize self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.page, serializer);
    sse_encode_u_64(self.raw, serializer);
    sse_encode_u_64(self.cover, serializer);
    sse_encode_u_64(self.thumb, serializer);
    sse_encode_u_64(self.ai, serializer);
    sse_encode_u_64(self.download, serializer);
    sse_encode_u_64(self.temp, serializer);
    sse_encode_u_64(self.total, serializer);
  }

  @protected
  void sse_encode_crop_rect(CropRect self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.x, serializer);
    sse_encode_f_64(self.y, serializer);
    sse_encode_f_64(self.w, serializer);
    sse_encode_f_64(self.h, serializer);
  }

  @protected
  void sse_encode_dir_entry(DirEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_bool(self.isDir, serializer);
    sse_encode_u_64(self.size, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_list_dir_entry(
    List<DirEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_dir_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_box_autoadd_crop_rect(
    CropRect? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_crop_rect(self, serializer);
    }
  }

  @protected
  void sse_encode_page_image(PageImage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.rgba, serializer);
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_web_dav_session(
    WebDavSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.id, serializer);
    sse_encode_String(self.root, serializer);
    sse_encode_String(self.capabilityLabel, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
