// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/book.dart';
import 'api/cache.dart';
import 'api/simple.dart';
import 'api/source.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  BookInfo dco_decode_book_info(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  CropRect dco_decode_box_autoadd_crop_rect(dynamic raw);

  @protected
  CacheSize dco_decode_cache_size(dynamic raw);

  @protected
  CropRect dco_decode_crop_rect(dynamic raw);

  @protected
  DirEntry dco_decode_dir_entry(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  List<DirEntry> dco_decode_list_dir_entry(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  CropRect? dco_decode_opt_box_autoadd_crop_rect(dynamic raw);

  @protected
  PageImage dco_decode_page_image(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  WebDavSession dco_decode_web_dav_session(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  BookInfo sse_decode_book_info(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  CropRect sse_decode_box_autoadd_crop_rect(SseDeserializer deserializer);

  @protected
  CacheSize sse_decode_cache_size(SseDeserializer deserializer);

  @protected
  CropRect sse_decode_crop_rect(SseDeserializer deserializer);

  @protected
  DirEntry sse_decode_dir_entry(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  List<DirEntry> sse_decode_list_dir_entry(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  CropRect? sse_decode_opt_box_autoadd_crop_rect(SseDeserializer deserializer);

  @protected
  PageImage sse_decode_page_image(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  WebDavSession sse_decode_web_dav_session(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_book_info(BookInfo self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_crop_rect(
    CropRect self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_cache_size(CacheSize self, SseSerializer serializer);

  @protected
  void sse_encode_crop_rect(CropRect self, SseSerializer serializer);

  @protected
  void sse_encode_dir_entry(DirEntry self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_list_dir_entry(List<DirEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_crop_rect(
    CropRect? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_page_image(PageImage self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_web_dav_session(WebDavSession self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
