// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class MaterializeResult {
  final String assetKey;
  final String bookKey;
  final String status;
  final List<String> changedFields;
  final List<String> addedTags;
  final List<String> skippedFields;
  final bool syncDirty;

  const MaterializeResult({
    required this.assetKey,
    required this.bookKey,
    required this.status,
    required this.changedFields,
    required this.addedTags,
    required this.skippedFields,
    required this.syncDirty,
  });

  @override
  int get hashCode =>
      assetKey.hashCode ^
      bookKey.hashCode ^
      status.hashCode ^
      changedFields.hashCode ^
      addedTags.hashCode ^
      skippedFields.hashCode ^
      syncDirty.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MaterializeResult &&
          runtimeType == other.runtimeType &&
          assetKey == other.assetKey &&
          bookKey == other.bookKey &&
          status == other.status &&
          changedFields == other.changedFields &&
          addedTags == other.addedTags &&
          skippedFields == other.skippedFields &&
          syncDirty == other.syncDirty;
}
