// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 对单张页面图片执行 AI 超分（默认 2x，scale 参数传给 CLI 的 -s）。
/// scale 参数用于传递给 CLI 的 -s 参数。
Future<Uint8List> superResolve({
  required List<int> pageBytes,
  required int scale,
}) => RustLib.instance.api.crateApiAiSuperResolve(
  pageBytes: pageBytes,
  scale: scale,
);

/// 查找已缓存的 AI 超分结果。
/// 若缓存存在，返回超分后的 JPEG；否则返回 null。
Future<Uint8List?> lookupCache({
  required List<int> pageBytes,
  required int scale,
}) => RustLib.instance.api.crateApiAiLookupCache(
  pageBytes: pageBytes,
  scale: scale,
);

/// 批量 AI 超分 — 一次 CLI 调用处理所有页。
Future<List<Uint8List>> superResolveBatch({
  required List<Uint8List> pages,
  required int scale,
}) => RustLib.instance.api.crateApiAiSuperResolveBatch(
  pages: pages,
  scale: scale,
);

/// 删除某页的 AI 超分缓存（取消整本超分时按页清理，不影响其他书）。
Future<void> deleteAiCacheForPage({
  required List<int> pageBytes,
  required int scale,
}) => RustLib.instance.api.crateApiAiDeleteAiCacheForPage(
  pageBytes: pageBytes,
  scale: scale,
);
