// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `next_id`, `register_book`, `sessions`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BookSession`

/// 打开本地书籍(ZIP/CBZ/EPUB),返回会话句柄与信息;并预取开头若干页。
/// 若 path 为目录,则走 Folder 格式(枚举目录下图片)。
Future<BookInfo> openLocalBook({required String path}) =>
    RustLib.instance.api.crateApiBookOpenLocalBook(path: path);

/// 读取一页的原始图片字节(优先命中缓存/预取,翻页秒出)。
/// 返回 ZIP 内该页的原始字节(JPEG/PNG 等);像素解码由 Flutter 侧完成(自带 image cache)。
Future<Uint8List> bookPage({required BigInt handle, required int index}) =>
    RustLib.instance.api.crateApiBookBookPage(handle: handle, index: index);

/// 生成书籍封面缩略图:取第 `page` 页,可按 `crop` 裁剪后缩放填充到 `w×h`。
/// 若 path 为目录,走 Folder 格式。
/// 生成本地书籍封面缩略图(取第 page 页,等比缩放 + 中心裁剪到 w×h)。
/// 封面结果写入磁盘缓存（cover/）供后续秒开。
Future<PageImage> bookCover({
  required String path,
  required int page,
  required int width,
  required int height,
  CropRect? crop,
}) => RustLib.instance.api.crateApiBookBookCover(
  path: path,
  page: page,
  width: width,
  height: height,
  crop: crop,
);

/// 关闭书籍会话,释放资源。
Future<void> closeBook({required BigInt handle}) =>
    RustLib.instance.api.crateApiBookCloseBook(handle: handle);

/// 列出本地目录内容(目录在前,自然排序)。
Future<List<DirEntry>> listLocalDir({required String path}) =>
    RustLib.instance.api.crateApiBookListLocalDir(path: path);

/// 检测目录是否为漫画文件夹（包含至少一张图片文件）。
/// 用于浏览页判断：是漫画文件夹 → 显示为海报卡片；否则 → 显示为普通文件夹。
Future<bool> isComicFolder({required String dirPath}) =>
    RustLib.instance.api.crateApiBookIsComicFolder(dirPath: dirPath);

/// 获取漫画文件夹的显式封面路径（cover.jpg / cover.png 等）。
/// 无显式封面时返回空字符串。
Future<String> folderCoverPath({required String dirPath}) =>
    RustLib.instance.api.crateApiBookFolderCoverPath(dirPath: dirPath);

/// 书籍信息。
class BookInfo {
  final BigInt handle;
  final String title;
  final int pageCount;

  const BookInfo({
    required this.handle,
    required this.title,
    required this.pageCount,
  });

  @override
  int get hashCode => handle.hashCode ^ title.hashCode ^ pageCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookInfo &&
          runtimeType == other.runtimeType &&
          handle == other.handle &&
          title == other.title &&
          pageCount == other.pageCount;
}

/// 封面裁剪区域(相对坐标 0-1)。
class CropRect {
  final double x;
  final double y;
  final double w;
  final double h;

  const CropRect({
    required this.x,
    required this.y,
    required this.w,
    required this.h,
  });

  @override
  int get hashCode => x.hashCode ^ y.hashCode ^ w.hashCode ^ h.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CropRect &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y &&
          w == other.w &&
          h == other.h;
}

/// 目录条目(书架/浏览用)。
class DirEntry {
  final String name;
  final String path;
  final bool isDir;
  final BigInt size;

  const DirEntry({
    required this.name,
    required this.path,
    required this.isDir,
    required this.size,
  });

  @override
  int get hashCode =>
      name.hashCode ^ path.hashCode ^ isDir.hashCode ^ size.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DirEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          path == other.path &&
          isDir == other.isDir &&
          size == other.size;
}

/// 一页解码后的位图(RGBA8888)。
class PageImage {
  final Uint8List rgba;
  final int width;
  final int height;

  const PageImage({
    required this.rgba,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode => rgba.hashCode ^ width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PageImage &&
          runtimeType == other.runtimeType &&
          rgba == other.rgba &&
          width == other.width &&
          height == other.height;
}
