// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 获取所有缓存分类大小。
Future<CacheSize> cacheSizes() =>
    RustLib.instance.api.crateApiCacheCacheSizes();

/// 获取 L2 页面缓存大小（字节）。
Future<BigInt> pageCacheSize() =>
    RustLib.instance.api.crateApiCachePageCacheSize();

/// 获取所有缓存分类总占用（字节，不含数据库/日志等非缓存数据）。
Future<BigInt> totalCacheSize() =>
    RustLib.instance.api.crateApiCacheTotalCacheSize();

/// 清空 L2 页面缓存，返回释放的字节数。
Future<BigInt> clearPageCache() =>
    RustLib.instance.api.crateApiCacheClearPageCache();

/// 清空原始文件缓存（raw/），返回释放的字节数。
Future<BigInt> clearRawCache() =>
    RustLib.instance.api.crateApiCacheClearRawCache();

/// 清空封面缓存（cover/），返回释放的字节数。
Future<BigInt> clearCoverCache() =>
    RustLib.instance.api.crateApiCacheClearCoverCache();

/// 清空 AI 结果缓存（ai/），返回释放的字节数。
Future<BigInt> clearAiCache() =>
    RustLib.instance.api.crateApiCacheClearAiCache();

/// 清空 AI 超分临时文件（temp/），返回释放的字节数。
Future<BigInt> clearTempCache() =>
    RustLib.instance.api.crateApiCacheClearTempCache();

/// 清空全部缓存，返回释放的字节数。
Future<BigInt> clearAllCaches() =>
    RustLib.instance.api.crateApiCacheClearAllCaches();

/// 获取缓存根目录路径。
Future<String> cacheRootPath() =>
    RustLib.instance.api.crateApiCacheCacheRootPath();

/// 设置自定义缓存根目录（空字符串恢复默认）。
/// 调用方应确保已迁移旧数据后再调用。
Future<void> setCacheRootPath({required String path}) =>
    RustLib.instance.api.crateApiCacheSetCacheRootPath(path: path);

/// 获取默认缓存根目录（APPDATA/RCH），不受自定义路径影响。
Future<String> defaultCacheRootPath() =>
    RustLib.instance.api.crateApiCacheDefaultCacheRootPath();

/// 迁移应用根目录（database.db + cache/ + 根级文件），排除支持目录。
/// 成功返回复制的字节数；调用方随后 set_cache_root_path + delete_migrated_items。
Future<BigInt> migrateCacheRoot({
  required String from,
  required String to,
  required String supportDir,
}) => RustLib.instance.api.crateApiCacheMigrateCacheRoot(
  from: from,
  to: to,
  supportDir: supportDir,
);

/// 迁移进度（已复制字节, 总字节），供 Dart 轮询。
Future<(BigInt, BigInt)> migrationProgress() =>
    RustLib.instance.api.crateApiCacheMigrationProgress();

/// 目标盘可用空间（字节）。路径不存在返回 0。
Future<BigInt> availableSpace({required String path}) =>
    RustLib.instance.api.crateApiCacheAvailableSpace(path: path);

/// 删除根目录下已迁移的项目（database.db、cache/），返回释放字节。
Future<BigInt> deleteMigratedItems({required String root}) =>
    RustLib.instance.api.crateApiCacheDeleteMigratedItems(root: root);

/// 读取未完成迁移标记（from, to）；无标记返回 null。
Future<(String, String)?> pendingMigration({required String root}) =>
    RustLib.instance.api.crateApiCachePendingMigration(root: root);

/// 清除迁移标记。
Future<void> clearMigrationMarker({required String root}) =>
    RustLib.instance.api.crateApiCacheClearMigrationMarker(root: root);

/// 缓存分类大小信息。
class CacheSize {
  /// 页面缓存(字节)，L2 磁盘页面缓存（page/）。
  final BigInt page;

  /// 整本下载缓存(字节)，远程书源整本下载（raw/）。
  final BigInt raw;

  /// 封面缓存(字节)，封面缩略图磁盘缓存（cover/）。
  final BigInt cover;

  /// AI 结果缓存(字节)（ai/）。
  final BigInt ai;

  /// 临时文件(字节)，AI 超分中间产物（temp/）。
  final BigInt temp;

  /// 所有缓存总和(字节)。
  final BigInt total;

  const CacheSize({
    required this.page,
    required this.raw,
    required this.cover,
    required this.ai,
    required this.temp,
    required this.total,
  });

  @override
  int get hashCode =>
      page.hashCode ^
      raw.hashCode ^
      cover.hashCode ^
      ai.hashCode ^
      temp.hashCode ^
      total.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CacheSize &&
          runtimeType == other.runtimeType &&
          page == other.page &&
          raw == other.raw &&
          cover == other.cover &&
          ai == other.ai &&
          temp == other.temp &&
          total == other.total;
}
