// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 数据是否已从 library.json 迁移到 SQLite。
Future<bool> dataIsMigrated() =>
    RustLib.instance.api.crateApiDbDataIsMigrated();

/// 从 library.json 全量导入 SQLite。`json_path` 为 library.json 完整路径。
/// 幂等：已迁移过的数据不重复导入。
Future<void> dataMigrateFromJson({required String jsonPath}) =>
    RustLib.instance.api.crateApiDbDataMigrateFromJson(jsonPath: jsonPath);

Future<List<BookSourceDto>> dbLoadAllSources() =>
    RustLib.instance.api.crateApiDbDbLoadAllSources();

Future<void> dbUpsertSource({required BookSourceDto source}) =>
    RustLib.instance.api.crateApiDbDbUpsertSource(source: source);

Future<void> dbDeleteSource({required String id}) =>
    RustLib.instance.api.crateApiDbDbDeleteSource(id: id);

Future<List<ReadRecordDto>> dbLoadAllRecords() =>
    RustLib.instance.api.crateApiDbDbLoadAllRecords();

Future<void> dbUpsertRecord({required ReadRecordDto record}) =>
    RustLib.instance.api.crateApiDbDbUpsertRecord(record: record);

Future<void> dbDeleteRecord({required String key}) =>
    RustLib.instance.api.crateApiDbDbDeleteRecord(key: key);

Future<int> dbDeleteRecordsBySourcePrefix({required String prefix}) => RustLib
    .instance
    .api
    .crateApiDbDbDeleteRecordsBySourcePrefix(prefix: prefix);

Future<List<BookMetaDto>> dbLoadAllMetas() =>
    RustLib.instance.api.crateApiDbDbLoadAllMetas();

Future<void> dbUpsertMeta({required BookMetaDto meta}) =>
    RustLib.instance.api.crateApiDbDbUpsertMeta(meta: meta);

Future<void> dbDeleteMeta({required String key}) =>
    RustLib.instance.api.crateApiDbDbDeleteMeta(key: key);

Future<int> dbDeleteMetasBySourcePrefix({required String prefix}) =>
    RustLib.instance.api.crateApiDbDbDeleteMetasBySourcePrefix(prefix: prefix);

Future<List<TagDto>> dbLoadAllTags() =>
    RustLib.instance.api.crateApiDbDbLoadAllTags();

Future<List<BookTagDto>> dbLoadAllBookTags() =>
    RustLib.instance.api.crateApiDbDbLoadAllBookTags();

/// 确保标签存在（幂等），返回标签 DTO。若标签已存在直接返回，否则创建。
Future<TagDto> dbEnsureTag({required String name}) =>
    RustLib.instance.api.crateApiDbDbEnsureTag(name: name);

/// 重命名标签（关联自动迁移）。
Future<void> dbRenameTag({required String oldName, required String newName}) =>
    RustLib.instance.api.crateApiDbDbRenameTag(
      oldName: oldName,
      newName: newName,
    );

/// 删除标签及所有关联。
Future<void> dbDeleteTag({required String name}) =>
    RustLib.instance.api.crateApiDbDbDeleteTag(name: name);

/// 将标签关联到一本书（幂等）。
Future<void> dbLinkTag({required String bookKey, required String tagName}) =>
    RustLib.instance.api.crateApiDbDbLinkTag(
      bookKey: bookKey,
      tagName: tagName,
    );

/// 将标签从一本书移除。
Future<void> dbUnlinkTag({required String bookKey, required String tagName}) =>
    RustLib.instance.api.crateApiDbDbUnlinkTag(
      bookKey: bookKey,
      tagName: tagName,
    );

/// 设置一本书的标签集（全量替换）。
Future<void> dbSetBookTags({
  required String bookKey,
  required List<String> tagNames,
}) => RustLib.instance.api.crateApiDbDbSetBookTags(
  bookKey: bookKey,
  tagNames: tagNames,
);

Future<List<SettingEntryDto>> dbLoadAllSettings() =>
    RustLib.instance.api.crateApiDbDbLoadAllSettings();

Future<void> dbSaveSetting({required String key, required String value}) =>
    RustLib.instance.api.crateApiDbDbSaveSetting(key: key, value: value);

Future<void> dbDeleteSetting({required String key}) =>
    RustLib.instance.api.crateApiDbDbDeleteSetting(key: key);

/// 漫画元数据 DTO。
class BookMetaDto {
  final String key;
  final int coverPage;
  final double? cropX;
  final double? cropY;
  final double? cropW;
  final double? cropH;
  final String author;
  final String genre;
  final String series;
  final String title;
  final String chineseTitle;
  final String summary;
  final String comment;

  const BookMetaDto({
    required this.key,
    required this.coverPage,
    this.cropX,
    this.cropY,
    this.cropW,
    this.cropH,
    required this.author,
    required this.genre,
    required this.series,
    required this.title,
    required this.chineseTitle,
    required this.summary,
    required this.comment,
  });

  @override
  int get hashCode =>
      key.hashCode ^
      coverPage.hashCode ^
      cropX.hashCode ^
      cropY.hashCode ^
      cropW.hashCode ^
      cropH.hashCode ^
      author.hashCode ^
      genre.hashCode ^
      series.hashCode ^
      title.hashCode ^
      chineseTitle.hashCode ^
      summary.hashCode ^
      comment.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookMetaDto &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          coverPage == other.coverPage &&
          cropX == other.cropX &&
          cropY == other.cropY &&
          cropW == other.cropW &&
          cropH == other.cropH &&
          author == other.author &&
          genre == other.genre &&
          series == other.series &&
          title == other.title &&
          chineseTitle == other.chineseTitle &&
          summary == other.summary &&
          comment == other.comment;
}

/// 书源 DTO（扁平结构，对应 Dart BookSource）。
class BookSourceDto {
  final String id;
  final String type;
  final String name;
  final String path;
  final String? url;
  final String? username;
  final String? password;
  final String note;
  final String capabilityLabel;

  const BookSourceDto({
    required this.id,
    required this.type,
    required this.name,
    required this.path,
    this.url,
    this.username,
    this.password,
    required this.note,
    required this.capabilityLabel,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      type.hashCode ^
      name.hashCode ^
      path.hashCode ^
      url.hashCode ^
      username.hashCode ^
      password.hashCode ^
      note.hashCode ^
      capabilityLabel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookSourceDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          type == other.type &&
          name == other.name &&
          path == other.path &&
          url == other.url &&
          username == other.username &&
          password == other.password &&
          note == other.note &&
          capabilityLabel == other.capabilityLabel;
}

/// 漫画-标签关联 DTO。
class BookTagDto {
  final String bookKey;
  final String tagId;

  const BookTagDto({required this.bookKey, required this.tagId});

  @override
  int get hashCode => bookKey.hashCode ^ tagId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookTagDto &&
          runtimeType == other.runtimeType &&
          bookKey == other.bookKey &&
          tagId == other.tagId;
}

/// 阅读记录 DTO。
class ReadRecordDto {
  final String key;
  final String sourceId;
  final String sourceType;
  final String path;
  final String title;
  final int lastPage;
  final int readCount;
  final PlatformInt64 lastReadAt;

  const ReadRecordDto({
    required this.key,
    required this.sourceId,
    required this.sourceType,
    required this.path,
    required this.title,
    required this.lastPage,
    required this.readCount,
    required this.lastReadAt,
  });

  @override
  int get hashCode =>
      key.hashCode ^
      sourceId.hashCode ^
      sourceType.hashCode ^
      path.hashCode ^
      title.hashCode ^
      lastPage.hashCode ^
      readCount.hashCode ^
      lastReadAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReadRecordDto &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          sourceId == other.sourceId &&
          sourceType == other.sourceType &&
          path == other.path &&
          title == other.title &&
          lastPage == other.lastPage &&
          readCount == other.readCount &&
          lastReadAt == other.lastReadAt;
}

/// 设置条目 DTO。
class SettingEntryDto {
  final String key;
  final String value;

  const SettingEntryDto({required this.key, required this.value});

  @override
  int get hashCode => key.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SettingEntryDto &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          value == other.value;
}

/// 标签实体 DTO。
class TagDto {
  final String id;
  final String name;
  final PlatformInt64 createdAt;

  const TagDto({required this.id, required this.name, required this.createdAt});

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TagDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          createdAt == other.createdAt;
}
