// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `library_index_to_dto`

/// 数据是否已从 library.json 迁移到 SQLite。
Future<bool> dataIsMigrated() =>
    RustLib.instance.api.crateApiDbDataIsMigrated();

/// 重开数据库连接（根目录切换后调用，使后续读写指向新根目录的数据库）。
Future<void> reopenDataDb() => RustLib.instance.api.crateApiDbReopenDataDb();

/// 从 library.json 全量导入 SQLite。`json_path` 为 library.json 完整路径。
/// 幂等：已迁移过的数据不重复导入。
Future<void> dataMigrateFromJson({required String jsonPath}) =>
    RustLib.instance.api.crateApiDbDataMigrateFromJson(jsonPath: jsonPath);

Future<List<BookSourceDto>> dbLoadAllSources() =>
    RustLib.instance.api.crateApiDbDbLoadAllSources();

Future<void> dbUpsertSource({required BookSourceDto source}) =>
    RustLib.instance.api.crateApiDbDbUpsertSource(source: source);

Future<void> dbDeleteSource({required String id}) =>
    RustLib.instance.api.crateApiDbDbDeleteSource(id: id);

Future<List<DeviceDto>> dbListDevices() =>
    RustLib.instance.api.crateApiDbDbListDevices();

Future<List<ReadRecordDto>> dbLoadAllRecords() =>
    RustLib.instance.api.crateApiDbDbLoadAllRecords();

Future<void> dbUpsertRecord({required ReadRecordDto record}) =>
    RustLib.instance.api.crateApiDbDbUpsertRecord(record: record);

Future<void> dbDeleteRecord({required String key}) =>
    RustLib.instance.api.crateApiDbDbDeleteRecord(key: key);

Future<int> dbDeleteRecordsBySourcePrefix({required String prefix}) => RustLib
    .instance
    .api
    .crateApiDbDbDeleteRecordsBySourcePrefix(prefix: prefix);

Future<List<BookMetaDto>> dbLoadAllMetas() =>
    RustLib.instance.api.crateApiDbDbLoadAllMetas();

Future<void> dbUpsertMeta({required BookMetaDto meta}) =>
    RustLib.instance.api.crateApiDbDbUpsertMeta(meta: meta);

Future<void> dbDeleteMeta({required String key}) =>
    RustLib.instance.api.crateApiDbDbDeleteMeta(key: key);

Future<int> dbDeleteMetasBySourcePrefix({required String prefix}) =>
    RustLib.instance.api.crateApiDbDbDeleteMetasBySourcePrefix(prefix: prefix);

Future<List<TagDto>> dbLoadAllTags() =>
    RustLib.instance.api.crateApiDbDbLoadAllTags();

Future<List<BookTagDto>> dbLoadAllBookTags() =>
    RustLib.instance.api.crateApiDbDbLoadAllBookTags();

/// 确保标签存在（幂等），返回标签 DTO。若标签已存在直接返回，否则创建。
Future<TagDto> dbEnsureTag({required String name}) =>
    RustLib.instance.api.crateApiDbDbEnsureTag(name: name);

/// 重命名标签（关联自动迁移）。
Future<void> dbRenameTag({required String oldName, required String newName}) =>
    RustLib.instance.api.crateApiDbDbRenameTag(
      oldName: oldName,
      newName: newName,
    );

/// 删除标签及所有关联。
Future<void> dbDeleteTag({required String name}) =>
    RustLib.instance.api.crateApiDbDbDeleteTag(name: name);

/// 将标签关联到一本书（幂等）。
Future<void> dbLinkTag({required String bookKey, required String tagName}) =>
    RustLib.instance.api.crateApiDbDbLinkTag(
      bookKey: bookKey,
      tagName: tagName,
    );

/// 将标签从一本书移除。
Future<void> dbUnlinkTag({required String bookKey, required String tagName}) =>
    RustLib.instance.api.crateApiDbDbUnlinkTag(
      bookKey: bookKey,
      tagName: tagName,
    );

/// 设置一本书的标签集（全量替换）。
Future<void> dbSetBookTags({
  required String bookKey,
  required List<String> tagNames,
}) => RustLib.instance.api.crateApiDbDbSetBookTags(
  bookKey: bookKey,
  tagNames: tagNames,
);

Future<List<SettingEntryDto>> dbLoadAllSettings() =>
    RustLib.instance.api.crateApiDbDbLoadAllSettings();

Future<void> dbSaveSetting({required String key, required String value}) =>
    RustLib.instance.api.crateApiDbDbSaveSetting(key: key, value: value);

/// 写入/更新 AI 超分任务。
Future<void> dbUpsertAiTask({required AiTaskDto task}) =>
    RustLib.instance.api.crateApiDbDbUpsertAiTask(task: task);

/// 加载全部 AI 超分任务。
Future<List<AiTaskDto>> dbLoadAllAiTasks() =>
    RustLib.instance.api.crateApiDbDbLoadAllAiTasks();

/// 按给定顺序重排排队任务的 sort_order（1..N）。调用方应只传排队中任务的 id。
Future<void> dbReorderAiTasks({required List<String> ids}) =>
    RustLib.instance.api.crateApiDbDbReorderAiTasks(ids: ids);

/// 删除 AI 超分任务。
Future<void> dbDeleteAiTask({required String id}) =>
    RustLib.instance.api.crateApiDbDbDeleteAiTask(id: id);

Future<void> dbDeleteSetting({required String key}) =>
    RustLib.instance.api.crateApiDbDbDeleteSetting(key: key);

/// 读取书源 fingerprint（无则 None；ADR-020：身份由 Rust 统一计算）。
Future<String?> dbGetSourceFingerprint({required String sourceId}) =>
    RustLib.instance.api.crateApiDbDbGetSourceFingerprint(sourceId: sourceId);

/// 批量 upsert library_index 条目（单事务）。
Future<void> dbUpsertLibraryIndexEntries({
  required List<LibraryIndexDto> entries,
}) => RustLib.instance.api.crateApiDbDbUpsertLibraryIndexEntries(
  entries: entries,
);

/// 整源重建（首次全量刷新 / 增量合并后替换）：
/// - 传入条目 upsert（deleted=0）；
/// - 该源旧索引中**不在新集合**的条目改为软删（deleted=1, updated_at=now），
///   使"文件消失"能以墓碑进入同步传播，而不是硬删除丢失历史。
Future<void> dbReplaceSourceLibraryIndex({
  required String sourceId,
  required List<LibraryIndexDto> entries,
}) => RustLib.instance.api.crateApiDbDbReplaceSourceLibraryIndex(
  sourceId: sourceId,
  entries: entries,
);

/// 写入书源目录快照（root_hash 用于判断目录是否变化）。
Future<void> dbSetSourceSnapshot({
  required String sourceId,
  required PlatformInt64 lastScanTime,
  required PlatformInt64 entryCount,
  String? rootHash,
}) => RustLib.instance.api.crateApiDbDbSetSourceSnapshot(
  sourceId: sourceId,
  lastScanTime: lastScanTime,
  entryCount: entryCount,
  rootHash: rootHash,
);

/// 读取书源目录快照。
Future<SourceSnapshotDto?> dbGetSourceSnapshot({required String sourceId}) =>
    RustLib.instance.api.crateApiDbDbGetSourceSnapshot(sourceId: sourceId);

/// 读取某书源当前（未删除）索引条目，离线浏览查询入口。
Future<List<LibraryIndexDto>> dbLoadLibraryIndexForSource({
  required String sourceId,
}) => RustLib.instance.api.crateApiDbDbLoadLibraryIndexForSource(
  sourceId: sourceId,
);

/// 补写一条索引条目（含父目录链；纯本地，零网络）。
/// ADR-029：缓存/已读/标签触及的漫画自动入离线索引。
Future<void> dbEnsureIndexEntry({
  required String sourceId,
  required String path,
  required String entryType,
  required String name,
  String? parentPath,
}) => RustLib.instance.api.crateApiDbDbEnsureIndexEntry(
  sourceId: sourceId,
  path: path,
  entryType: entryType,
  name: name,
  parentPath: parentPath,
);

/// 批量补写索引条目（同一书源一个事务；每条含父链）。
/// ADR-029：浏览即索引 / 从本地浏览快照生成离线索引。
Future<void> dbEnsureIndexEntries({
  required String sourceId,
  required List<IndexEntryInput> entries,
}) => RustLib.instance.api.crateApiDbDbEnsureIndexEntries(
  sourceId: sourceId,
  entries: entries,
);

/// AI 超分后台任务 DTO。
class AiTaskDto {
  final String id;
  final String bookKey;
  final String sourceType;
  final String sourceId;
  final String path;
  final String title;
  final PlatformInt64 scale;
  final PlatformInt64 total;
  final PlatformInt64 done;
  final String status;
  final PlatformInt64 sortOrder;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;

  const AiTaskDto({
    required this.id,
    required this.bookKey,
    required this.sourceType,
    required this.sourceId,
    required this.path,
    required this.title,
    required this.scale,
    required this.total,
    required this.done,
    required this.status,
    required this.sortOrder,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      bookKey.hashCode ^
      sourceType.hashCode ^
      sourceId.hashCode ^
      path.hashCode ^
      title.hashCode ^
      scale.hashCode ^
      total.hashCode ^
      done.hashCode ^
      status.hashCode ^
      sortOrder.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiTaskDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          bookKey == other.bookKey &&
          sourceType == other.sourceType &&
          sourceId == other.sourceId &&
          path == other.path &&
          title == other.title &&
          scale == other.scale &&
          total == other.total &&
          done == other.done &&
          status == other.status &&
          sortOrder == other.sortOrder &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

/// 漫画元数据 DTO。
class BookMetaDto {
  final String key;
  final int coverPage;
  final double? cropX;
  final double? cropY;
  final double? cropW;
  final double? cropH;
  final String author;
  final String genre;
  final String series;
  final String title;
  final String chineseTitle;
  final String summary;
  final String comment;

  /// 每页旋转（JSON 文本，如 {"0":90}）。
  final String rotations;

  const BookMetaDto({
    required this.key,
    required this.coverPage,
    this.cropX,
    this.cropY,
    this.cropW,
    this.cropH,
    required this.author,
    required this.genre,
    required this.series,
    required this.title,
    required this.chineseTitle,
    required this.summary,
    required this.comment,
    required this.rotations,
  });

  @override
  int get hashCode =>
      key.hashCode ^
      coverPage.hashCode ^
      cropX.hashCode ^
      cropY.hashCode ^
      cropW.hashCode ^
      cropH.hashCode ^
      author.hashCode ^
      genre.hashCode ^
      series.hashCode ^
      title.hashCode ^
      chineseTitle.hashCode ^
      summary.hashCode ^
      comment.hashCode ^
      rotations.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookMetaDto &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          coverPage == other.coverPage &&
          cropX == other.cropX &&
          cropY == other.cropY &&
          cropW == other.cropW &&
          cropH == other.cropH &&
          author == other.author &&
          genre == other.genre &&
          series == other.series &&
          title == other.title &&
          chineseTitle == other.chineseTitle &&
          summary == other.summary &&
          comment == other.comment &&
          rotations == other.rotations;
}

/// 书源 DTO（扁平结构，对应 Dart BookSource）。
class BookSourceDto {
  final String id;
  final String type;
  final String name;
  final String path;
  final String? url;
  final String? username;
  final String? password;
  final PlatformInt64? port;
  final String? refreshToken;
  final String? clientId;
  final String? clientSecret;
  final String? rootId;
  final String? cookie;
  final String note;
  final String capabilityLabel;
  final bool remoteOnly;
  final String? originDeviceId;

  const BookSourceDto({
    required this.id,
    required this.type,
    required this.name,
    required this.path,
    this.url,
    this.username,
    this.password,
    this.port,
    this.refreshToken,
    this.clientId,
    this.clientSecret,
    this.rootId,
    this.cookie,
    required this.note,
    required this.capabilityLabel,
    required this.remoteOnly,
    this.originDeviceId,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      type.hashCode ^
      name.hashCode ^
      path.hashCode ^
      url.hashCode ^
      username.hashCode ^
      password.hashCode ^
      port.hashCode ^
      refreshToken.hashCode ^
      clientId.hashCode ^
      clientSecret.hashCode ^
      rootId.hashCode ^
      cookie.hashCode ^
      note.hashCode ^
      capabilityLabel.hashCode ^
      remoteOnly.hashCode ^
      originDeviceId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookSourceDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          type == other.type &&
          name == other.name &&
          path == other.path &&
          url == other.url &&
          username == other.username &&
          password == other.password &&
          port == other.port &&
          refreshToken == other.refreshToken &&
          clientId == other.clientId &&
          clientSecret == other.clientSecret &&
          rootId == other.rootId &&
          cookie == other.cookie &&
          note == other.note &&
          capabilityLabel == other.capabilityLabel &&
          remoteOnly == other.remoteOnly &&
          originDeviceId == other.originDeviceId;
}

/// 漫画-标签关联 DTO。
class BookTagDto {
  final String bookKey;
  final String tagId;

  const BookTagDto({required this.bookKey, required this.tagId});

  @override
  int get hashCode => bookKey.hashCode ^ tagId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookTagDto &&
          runtimeType == other.runtimeType &&
          bookKey == other.bookKey &&
          tagId == other.tagId;
}

/// 设备注册表条目（幽灵书源来源展示）。
class DeviceDto {
  final String id;
  final String name;

  const DeviceDto({required this.id, required this.name});

  @override
  int get hashCode => id.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name;
}

/// 补写索引条目的输入（id/parent 由 Rust 按 book_id 规则计算，调用方只给路径语义）。
class IndexEntryInput {
  final String path;
  final String entryType;
  final String name;
  final PlatformInt64? size;
  final PlatformInt64? modifiedAt;

  /// 显式父目录（扁平路径源如夸克/115 必传；None = 从 path 推导）。
  final String? parentPath;

  const IndexEntryInput({
    required this.path,
    required this.entryType,
    required this.name,
    this.size,
    this.modifiedAt,
    this.parentPath,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      entryType.hashCode ^
      name.hashCode ^
      size.hashCode ^
      modifiedAt.hashCode ^
      parentPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IndexEntryInput &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          entryType == other.entryType &&
          name == other.name &&
          size == other.size &&
          modifiedAt == other.modifiedAt &&
          parentPath == other.parentPath;
}

/// library_index 条目 DTO（与 Dart LibraryIndexEntry 对应）。
class LibraryIndexDto {
  final String id;
  final String sourceId;
  final String? parentId;
  final String name;
  final String path;
  final String entryType;
  final PlatformInt64? size;
  final PlatformInt64? modifiedAt;
  final String? coverPath;
  final String? hash;
  final PlatformInt64 updatedAt;
  final bool deleted;

  const LibraryIndexDto({
    required this.id,
    required this.sourceId,
    this.parentId,
    required this.name,
    required this.path,
    required this.entryType,
    this.size,
    this.modifiedAt,
    this.coverPath,
    this.hash,
    required this.updatedAt,
    required this.deleted,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      sourceId.hashCode ^
      parentId.hashCode ^
      name.hashCode ^
      path.hashCode ^
      entryType.hashCode ^
      size.hashCode ^
      modifiedAt.hashCode ^
      coverPath.hashCode ^
      hash.hashCode ^
      updatedAt.hashCode ^
      deleted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LibraryIndexDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          sourceId == other.sourceId &&
          parentId == other.parentId &&
          name == other.name &&
          path == other.path &&
          entryType == other.entryType &&
          size == other.size &&
          modifiedAt == other.modifiedAt &&
          coverPath == other.coverPath &&
          hash == other.hash &&
          updatedAt == other.updatedAt &&
          deleted == other.deleted;
}

/// 阅读记录 DTO。
class ReadRecordDto {
  final String key;
  final String sourceId;
  final String sourceType;
  final String path;
  final String title;
  final int lastPage;
  final int readCount;
  final PlatformInt64 lastReadAt;

  const ReadRecordDto({
    required this.key,
    required this.sourceId,
    required this.sourceType,
    required this.path,
    required this.title,
    required this.lastPage,
    required this.readCount,
    required this.lastReadAt,
  });

  @override
  int get hashCode =>
      key.hashCode ^
      sourceId.hashCode ^
      sourceType.hashCode ^
      path.hashCode ^
      title.hashCode ^
      lastPage.hashCode ^
      readCount.hashCode ^
      lastReadAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReadRecordDto &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          sourceId == other.sourceId &&
          sourceType == other.sourceType &&
          path == other.path &&
          title == other.title &&
          lastPage == other.lastPage &&
          readCount == other.readCount &&
          lastReadAt == other.lastReadAt;
}

/// 设置条目 DTO。
class SettingEntryDto {
  final String key;
  final String value;

  const SettingEntryDto({required this.key, required this.value});

  @override
  int get hashCode => key.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SettingEntryDto &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          value == other.value;
}

/// 书源目录快照 DTO。
class SourceSnapshotDto {
  final String sourceId;
  final PlatformInt64 lastScanTime;
  final PlatformInt64 entryCount;
  final String? rootHash;

  const SourceSnapshotDto({
    required this.sourceId,
    required this.lastScanTime,
    required this.entryCount,
    this.rootHash,
  });

  @override
  int get hashCode =>
      sourceId.hashCode ^
      lastScanTime.hashCode ^
      entryCount.hashCode ^
      rootHash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SourceSnapshotDto &&
          runtimeType == other.runtimeType &&
          sourceId == other.sourceId &&
          lastScanTime == other.lastScanTime &&
          entryCount == other.entryCount &&
          rootHash == other.rootHash;
}

/// 标签实体 DTO。
class TagDto {
  final String id;
  final String name;
  final PlatformInt64 createdAt;

  const TagDto({required this.id, required this.name, required this.createdAt});

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TagDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          createdAt == other.createdAt;
}
