// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `rules_from_arg`

/// 默认规则 JSON（首次打开订阅面板时使用）。
Future<String> ehDefaultRules() =>
    RustLib.instance.api.crateApiEhSubscriptionEhDefaultRules();

/// 读取规则文件；文件不存在时回写默认规则并返回默认值。
Future<String> ehLoadRules({required String path}) =>
    RustLib.instance.api.crateApiEhSubscriptionEhLoadRules(path: path);

/// 保存规则 JSON（先校验再落盘，避免写出损坏配置）。
Future<void> ehSaveRules({required String path, required String rulesJson}) =>
    RustLib.instance.api.crateApiEhSubscriptionEhSaveRules(
      path: path,
      rulesJson: rulesJson,
    );

/// 当前扫描进度（UI 轮询；JSON 编码避免为进度单独生成 DTO）。
Future<String> ehProgress() =>
    RustLib.instance.api.crateApiEhSubscriptionEhProgress();

/// 请求取消当前扫描（在下一个候选边界生效）。
Future<void> ehCancel() =>
    RustLib.instance.api.crateApiEhSubscriptionEhCancel();

/// 连通性预检：主站与 tracker 分别是否可达（国内网络下主站常需代理）。
Future<String> ehProbe({required String rulesJson}) =>
    RustLib.instance.api.crateApiEhSubscriptionEhProbe(rulesJson: rulesJson);

/// 执行一轮扫描。返回的是结束后的一次进度快照（UI 亦可轮询 `eh_progress`）。
Future<String> ehCollect({required String rulesJson}) =>
    RustLib.instance.api.crateApiEhSubscriptionEhCollect(rulesJson: rulesJson);

/// 读取已保存清单（文件不存在返回空列表）。
Future<String> ehManifest({required String outDir}) =>
    RustLib.instance.api.crateApiEhSubscriptionEhManifest(outDir: outDir);
