// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `rules_from_arg`

/// 默认规则 JSON（首次打开订阅面板时使用）。
Future<String> ehDefaultRules() =>
    RustLib.instance.api.crateApiEhSubscriptionEhDefaultRules();

/// 读取规则文件；文件不存在时回写默认规则并返回默认值。
Future<String> ehLoadRules({required String path}) =>
    RustLib.instance.api.crateApiEhSubscriptionEhLoadRules(path: path);

/// 保存规则 JSON（先校验再落盘，避免写出损坏配置）。
Future<void> ehSaveRules({required String path, required String rulesJson}) =>
    RustLib.instance.api.crateApiEhSubscriptionEhSaveRules(
      path: path,
      rulesJson: rulesJson,
    );

/// 当前扫描进度（UI 轮询；JSON 编码避免为进度单独生成 DTO）。
Future<String> ehProgress() =>
    RustLib.instance.api.crateApiEhSubscriptionEhProgress();

/// 请求取消当前扫描（在下一个候选边界生效）。
Future<void> ehCancel() =>
    RustLib.instance.api.crateApiEhSubscriptionEhCancel();

/// 连通性预检：主站与 tracker 分别是否可达（国内网络下主站常需代理）。
Future<String> ehProbe({required String rulesJson}) =>
    RustLib.instance.api.crateApiEhSubscriptionEhProbe(rulesJson: rulesJson);

/// 执行一轮扫描。返回的是结束后的一次进度快照（UI 亦可轮询 `eh_progress`）。
Future<String> ehCollect({required String rulesJson}) =>
    RustLib.instance.api.crateApiEhSubscriptionEhCollect(rulesJson: rulesJson);

/// **实时搜索**规划一本书的导入（影子模式，不写库）。
///
/// 与 `eh_plan_import`（读 manifest、离线）不同：候选来自**实时搜索 E 站**
/// （锚点依次尝试 → gdata → Dice 判定），因此不受"manifest 只含订阅命中项"的限制，
/// 这是修复"大多数书识别不出来"的关键。
/// 命中后会带回画廊语义层（标签/作者/系列/语言…），缺失译名时按需联网更新。
Future<String> ehPlanBookLive({
  required String rulesJson,
  required String workTitle,
  required String creatorsJson,
  required String snapshotJson,
}) => RustLib.instance.api.crateApiEhSubscriptionEhPlanBookLive(
  rulesJson: rulesJson,
  workTitle: workTitle,
  creatorsJson: creatorsJson,
  snapshotJson: snapshotJson,
);

/// 影子模式：从已落盘的 manifest 规划"将要导入什么"（**不写库**）。
///
/// 候选直接取自 manifest 的语义层，因此**离线可复现**（不联网搜索）。
/// `creators_json` 为本地作品名之外的兜底锚点（JSON 字符串数组）；
/// `snapshot_json` 为本地现状（`eh_import::BookSnapshot`）。
Future<String> ehPlanImport({
  required String manifestDir,
  required String workTitle,
  required String creatorsJson,
  required String snapshotJson,
}) => RustLib.instance.api.crateApiEhSubscriptionEhPlanImport(
  manifestDir: manifestDir,
  workTitle: workTitle,
  creatorsJson: creatorsJson,
  snapshotJson: snapshotJson,
);

/// 读取已保存清单（文件不存在返回空列表）。
Future<String> ehManifest({required String outDir}) =>
    RustLib.instance.api.crateApiEhSubscriptionEhManifest(outDir: outDir);
