// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `export_folder_to_cbz_impl`, `is_image_name`

/// 文件夹 → CBZ：按自然排序打包顶层图片，附带 ComicInfo.xml / metadata.json。
Future<void> exportFolderToCbz({
  required String srcDir,
  required String outPath,
}) => RustLib.instance.api.crateApiExportExportFolderToCbz(
  srcDir: srcDir,
  outPath: outPath,
);

/// ZIP/CBZ → CBZ：同容器，直接复制字节即可。
Future<void> exportZipAsCbz({
  required String srcPath,
  required String outPath,
}) => RustLib.instance.api.crateApiExportExportZipAsCbz(
  srcPath: srcPath,
  outPath: outPath,
);
