// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_book_query`, `cloud_has_credentials`, `run_book_query`, `source_status`

/// 某书源离线索引总数（浏览模式判定：有索引 → 离线优先）。
Future<PlatformInt64> dbSourceIndexCount({required String sourceId}) =>
    RustLib.instance.api.crateApiLibraryDbSourceIndexCount(sourceId: sourceId);

/// 某书源目录的直接子条目（离线浏览；parent_id = book_id(fingerprint, dir)）。
Future<List<LibEntryDto>> dbSourceDirEntries({
  required String sourceId,
  required String dirPath,
}) => RustLib.instance.api.crateApiLibraryDbSourceDirEntries(
  sourceId: sourceId,
  dirPath: dirPath,
);

/// 设备 → 书源树（本机逻辑书源 + 远端书源按设备分组）。
Future<List<SourceTreeNodeDto>> dbSourceTree() =>
    RustLib.instance.api.crateApiLibraryDbSourceTree();

/// 跨设备资料库搜索（分页；直接走 SQL，不整载 library_index）。
Future<List<BookSearchDto>> dbSearchBooks({
  required String query,
  required List<String> tags,
  required bool includeRemote,
  required PlatformInt64 limit,
  required PlatformInt64 offset,
}) => RustLib.instance.api.crateApiLibraryDbSearchBooks(
  query: query,
  tags: tags,
  includeRemote: includeRemote,
  limit: limit,
  offset: offset,
);

/// 某书源下的漫画（分页；三级树书源节点展开时懒加载）。
Future<List<BookSearchDto>> dbSourceBooks({
  required String sourceId,
  required String query,
  required List<String> tags,
  required PlatformInt64 limit,
  required PlatformInt64 offset,
}) => RustLib.instance.api.crateApiLibraryDbSourceBooks(
  sourceId: sourceId,
  query: query,
  tags: tags,
  limit: limit,
  offset: offset,
);

/// 漫画搜索结果（跨设备资料库检索）。
class BookSearchDto {
  final String bookId;
  final String sourceId;
  final String sourceName;
  final String sourceType;
  final String path;
  final String title;
  final String deviceId;
  final String deviceName;
  final bool isRemote;
  final String status;
  final PlatformInt64 lastReadAt;
  final String tags;

  const BookSearchDto({
    required this.bookId,
    required this.sourceId,
    required this.sourceName,
    required this.sourceType,
    required this.path,
    required this.title,
    required this.deviceId,
    required this.deviceName,
    required this.isRemote,
    required this.status,
    required this.lastReadAt,
    required this.tags,
  });

  @override
  int get hashCode =>
      bookId.hashCode ^
      sourceId.hashCode ^
      sourceName.hashCode ^
      sourceType.hashCode ^
      path.hashCode ^
      title.hashCode ^
      deviceId.hashCode ^
      deviceName.hashCode ^
      isRemote.hashCode ^
      status.hashCode ^
      lastReadAt.hashCode ^
      tags.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookSearchDto &&
          runtimeType == other.runtimeType &&
          bookId == other.bookId &&
          sourceId == other.sourceId &&
          sourceName == other.sourceName &&
          sourceType == other.sourceType &&
          path == other.path &&
          title == other.title &&
          deviceId == other.deviceId &&
          deviceName == other.deviceName &&
          isRemote == other.isRemote &&
          status == other.status &&
          lastReadAt == other.lastReadAt &&
          tags == other.tags;
}

/// library_index 目录条目（书源内离线浏览）。
class LibEntryDto {
  final String id;
  final String name;
  final String path;
  final String entryType;
  final PlatformInt64? size;
  final PlatformInt64? modifiedAt;
  final String? coverPath;
  final String? hash;

  const LibEntryDto({
    required this.id,
    required this.name,
    required this.path,
    required this.entryType,
    this.size,
    this.modifiedAt,
    this.coverPath,
    this.hash,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      path.hashCode ^
      entryType.hashCode ^
      size.hashCode ^
      modifiedAt.hashCode ^
      coverPath.hashCode ^
      hash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LibEntryDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          path == other.path &&
          entryType == other.entryType &&
          size == other.size &&
          modifiedAt == other.modifiedAt &&
          coverPath == other.coverPath &&
          hash == other.hash;
}

/// 书源可用性（设备树节点）。
class SourceAvailabilityDto {
  final String sourceId;
  final String fingerprint;
  final String name;
  final String type;

  /// 书源根路径（离线浏览/在线浏览的初始目录；ADR-028 §12.5 兜底不再用 '/'）。
  final String path;

  /// 本机配置的书源（非同步进来的远端行）。
  final bool hasLocalSource;

  /// 本地/SMB 路径在本机存在。
  final bool hasLocalResource;

  /// 本机具备该书源所需凭据（云端）。
  final bool hasCredentials;
  final String deviceId;
  final String deviceName;
  final bool isRemote;

  /// 离线索引条目数（可离线浏览）。
  final PlatformInt64 offlineIndexCount;
  final bool canBrowseOffline;
  final bool requiresNetwork;

  /// "read" | "needs_network" | "index_only"
  final String status;

  const SourceAvailabilityDto({
    required this.sourceId,
    required this.fingerprint,
    required this.name,
    required this.type,
    required this.path,
    required this.hasLocalSource,
    required this.hasLocalResource,
    required this.hasCredentials,
    required this.deviceId,
    required this.deviceName,
    required this.isRemote,
    required this.offlineIndexCount,
    required this.canBrowseOffline,
    required this.requiresNetwork,
    required this.status,
  });

  @override
  int get hashCode =>
      sourceId.hashCode ^
      fingerprint.hashCode ^
      name.hashCode ^
      type.hashCode ^
      path.hashCode ^
      hasLocalSource.hashCode ^
      hasLocalResource.hashCode ^
      hasCredentials.hashCode ^
      deviceId.hashCode ^
      deviceName.hashCode ^
      isRemote.hashCode ^
      offlineIndexCount.hashCode ^
      canBrowseOffline.hashCode ^
      requiresNetwork.hashCode ^
      status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SourceAvailabilityDto &&
          runtimeType == other.runtimeType &&
          sourceId == other.sourceId &&
          fingerprint == other.fingerprint &&
          name == other.name &&
          type == other.type &&
          path == other.path &&
          hasLocalSource == other.hasLocalSource &&
          hasLocalResource == other.hasLocalResource &&
          hasCredentials == other.hasCredentials &&
          deviceId == other.deviceId &&
          deviceName == other.deviceName &&
          isRemote == other.isRemote &&
          offlineIndexCount == other.offlineIndexCount &&
          canBrowseOffline == other.canBrowseOffline &&
          requiresNetwork == other.requiresNetwork &&
          status == other.status;
}

/// 设备 → 书源树节点。
class SourceTreeNodeDto {
  final String deviceId;
  final String deviceName;
  final List<SourceAvailabilityDto> sources;

  const SourceTreeNodeDto({
    required this.deviceId,
    required this.deviceName,
    required this.sources,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^ deviceName.hashCode ^ sources.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SourceTreeNodeDto &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          deviceName == other.deviceName &&
          sources == other.sources;
}
