// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`

/// 导出标准包到文件。`incremental=true` 时只导出自上次游标以来的变更。
Future<SyncExportInfo> rchpkgExport({
  required String path,
  required bool incremental,
}) => RustLib.instance.api.crateApiPackageRchpkgExport(
  path: path,
  incremental: incremental,
);

/// 合并/导入标准包。`force=true` 恢复（包覆盖，凭据保留）；`false` 拉取合并（LWW + 墓碑）。
Future<SyncImportStats> rchpkgImport({
  required String path,
  required bool force,
}) =>
    RustLib.instance.api.crateApiPackageRchpkgImport(path: path, force: force);

/// 导出标准包并附带加密凭据分块（凭据 AES-256-GCM + 口令派生，按 fingerprint 匹配）。
Future<SyncExportInfo> rchpkgExportWithCredentials({
  required String path,
  required bool incremental,
  required String passphrase,
}) => RustLib.instance.api.crateApiPackageRchpkgExportWithCredentials(
  path: path,
  incremental: incremental,
  passphrase: passphrase,
);

/// 导出全量快照包到文件（手动"导出到文件"），**不推进**增量游标，
/// 避免污染后续 push 的基线；`passphrase` 为空导出不含凭据的包，
/// 非空附带 AES-256-GCM 加密凭据分块。
Future<SyncExportInfo> rchpkgExportSnapshot({
  required String path,
  required String passphrase,
}) => RustLib.instance.api.crateApiPackageRchpkgExportSnapshot(
  path: path,
  passphrase: passphrase,
);

/// 导入标准包并应用加密凭据分块（需口令，口令错误则整体中止）。
Future<SyncImportStats> rchpkgImportWithCredentials({
  required String path,
  required String passphrase,
}) => RustLib.instance.api.crateApiPackageRchpkgImportWithCredentials(
  path: path,
  passphrase: passphrase,
);

/// 默认同步目录约定：`<root>/RCH/sync`。
Future<String> rchpkgDefaultSyncDir({required String root}) =>
    RustLib.instance.api.crateApiPackageRchpkgDefaultSyncDir(root: root);

/// 加密导出"书源凭据包"：返回 JSON 文本（AES-256-GCM + 口令派生）。
Future<String> sourceBundleEncrypt({
  required String passphrase,
  required List<SourceBundleDto> sources,
}) => RustLib.instance.api.crateApiPackageSourceBundleEncrypt(
  passphrase: passphrase,
  sources: sources,
);

/// 解密"书源凭据包"：口令错误或数据损坏会报错。
Future<List<SourceBundleDto>> sourceBundleDecrypt({
  required String passphrase,
  required String data,
}) => RustLib.instance.api.crateApiPackageSourceBundleDecrypt(
  passphrase: passphrase,
  data: data,
);

/// 书源凭据包条目（加密导入用）。
class SourceBundleDto {
  final String id;
  final String type;
  final String name;
  final String path;
  final String? url;
  final String? username;
  final PlatformInt64? port;
  final String? clientId;
  final String? rootId;
  final String? password;
  final String? refreshToken;
  final String? clientSecret;
  final String? cookie;
  final String note;

  const SourceBundleDto({
    required this.id,
    required this.type,
    required this.name,
    required this.path,
    this.url,
    this.username,
    this.port,
    this.clientId,
    this.rootId,
    this.password,
    this.refreshToken,
    this.clientSecret,
    this.cookie,
    required this.note,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      type.hashCode ^
      name.hashCode ^
      path.hashCode ^
      url.hashCode ^
      username.hashCode ^
      port.hashCode ^
      clientId.hashCode ^
      rootId.hashCode ^
      password.hashCode ^
      refreshToken.hashCode ^
      clientSecret.hashCode ^
      cookie.hashCode ^
      note.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SourceBundleDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          type == other.type &&
          name == other.name &&
          path == other.path &&
          url == other.url &&
          username == other.username &&
          port == other.port &&
          clientId == other.clientId &&
          rootId == other.rootId &&
          password == other.password &&
          refreshToken == other.refreshToken &&
          clientSecret == other.clientSecret &&
          cookie == other.cookie &&
          note == other.note;
}

/// 导出结果统计。
class SyncExportInfo {
  final String deviceId;
  final PlatformInt64 createdAt;
  final PlatformInt64 since;
  final PlatformInt64 tags;
  final PlatformInt64 bookTags;
  final PlatformInt64 metas;
  final PlatformInt64 records;
  final PlatformInt64 sources;
  final PlatformInt64 settings;
  final PlatformInt64 tombstones;

  const SyncExportInfo({
    required this.deviceId,
    required this.createdAt,
    required this.since,
    required this.tags,
    required this.bookTags,
    required this.metas,
    required this.records,
    required this.sources,
    required this.settings,
    required this.tombstones,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      createdAt.hashCode ^
      since.hashCode ^
      tags.hashCode ^
      bookTags.hashCode ^
      metas.hashCode ^
      records.hashCode ^
      sources.hashCode ^
      settings.hashCode ^
      tombstones.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncExportInfo &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          createdAt == other.createdAt &&
          since == other.since &&
          tags == other.tags &&
          bookTags == other.bookTags &&
          metas == other.metas &&
          records == other.records &&
          sources == other.sources &&
          settings == other.settings &&
          tombstones == other.tombstones;
}

/// 导入结果统计。
class SyncImportStats {
  final PlatformInt64 schemaVersion;
  final PlatformInt64 tags;
  final PlatformInt64 bookTags;
  final PlatformInt64 metas;
  final PlatformInt64 records;
  final PlatformInt64 sources;
  final PlatformInt64 settings;
  final PlatformInt64 tombstones;
  final PlatformInt64 ghosts;
  final PlatformInt64 skipped;

  const SyncImportStats({
    required this.schemaVersion,
    required this.tags,
    required this.bookTags,
    required this.metas,
    required this.records,
    required this.sources,
    required this.settings,
    required this.tombstones,
    required this.ghosts,
    required this.skipped,
  });

  @override
  int get hashCode =>
      schemaVersion.hashCode ^
      tags.hashCode ^
      bookTags.hashCode ^
      metas.hashCode ^
      records.hashCode ^
      sources.hashCode ^
      settings.hashCode ^
      tombstones.hashCode ^
      ghosts.hashCode ^
      skipped.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncImportStats &&
          runtimeType == other.runtimeType &&
          schemaVersion == other.schemaVersion &&
          tags == other.tags &&
          bookTags == other.bookTags &&
          metas == other.metas &&
          records == other.records &&
          sources == other.sources &&
          settings == other.settings &&
          tombstones == other.tombstones &&
          ghosts == other.ghosts &&
          skipped == other.skipped;
}
