// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 导出标准包到文件。`incremental=true` 时只导出自上次游标以来的变更。
Future<SyncExportInfo> rchpkgExport({
  required String path,
  required bool incremental,
}) => RustLib.instance.api.crateApiPackageRchpkgExport(
  path: path,
  incremental: incremental,
);

/// 从文件导入标准包（保留目标端书源凭据；schema 不兼容时拒绝）。
Future<SyncImportStats> rchpkgImport({required String path}) =>
    RustLib.instance.api.crateApiPackageRchpkgImport(path: path);

/// 默认同步目录约定：`<root>/RCH/sync`。
Future<String> rchpkgDefaultSyncDir({required String root}) =>
    RustLib.instance.api.crateApiPackageRchpkgDefaultSyncDir(root: root);

/// 导出结果统计。
class SyncExportInfo {
  final String deviceId;
  final PlatformInt64 createdAt;
  final PlatformInt64 since;
  final PlatformInt64 tags;
  final PlatformInt64 bookTags;
  final PlatformInt64 metas;
  final PlatformInt64 records;
  final PlatformInt64 sources;
  final PlatformInt64 settings;
  final PlatformInt64 tombstones;

  const SyncExportInfo({
    required this.deviceId,
    required this.createdAt,
    required this.since,
    required this.tags,
    required this.bookTags,
    required this.metas,
    required this.records,
    required this.sources,
    required this.settings,
    required this.tombstones,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      createdAt.hashCode ^
      since.hashCode ^
      tags.hashCode ^
      bookTags.hashCode ^
      metas.hashCode ^
      records.hashCode ^
      sources.hashCode ^
      settings.hashCode ^
      tombstones.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncExportInfo &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          createdAt == other.createdAt &&
          since == other.since &&
          tags == other.tags &&
          bookTags == other.bookTags &&
          metas == other.metas &&
          records == other.records &&
          sources == other.sources &&
          settings == other.settings &&
          tombstones == other.tombstones;
}

/// 导入结果统计。
class SyncImportStats {
  final PlatformInt64 schemaVersion;
  final PlatformInt64 tags;
  final PlatformInt64 bookTags;
  final PlatformInt64 metas;
  final PlatformInt64 records;
  final PlatformInt64 sources;
  final PlatformInt64 settings;

  const SyncImportStats({
    required this.schemaVersion,
    required this.tags,
    required this.bookTags,
    required this.metas,
    required this.records,
    required this.sources,
    required this.settings,
  });

  @override
  int get hashCode =>
      schemaVersion.hashCode ^
      tags.hashCode ^
      bookTags.hashCode ^
      metas.hashCode ^
      records.hashCode ^
      sources.hashCode ^
      settings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncImportStats &&
          runtimeType == other.runtimeType &&
          schemaVersion == other.schemaVersion &&
          tags == other.tags &&
          bookTags == other.bookTags &&
          metas == other.metas &&
          records == other.records &&
          sources == other.sources &&
          settings == other.settings;
}
