// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 设置 pdfium 原生库所在目录（Android：`ApplicationInfo.nativeLibraryDir`）。
/// 调用后打开 PDF 时优先从该目录加载 `libpdfium.so`；Windows 桌面端无需调用。
Future<void> setNativeLibDir({required String dir}) =>
    RustLib.instance.api.crateApiPdfSetNativeLibDir(dir: dir);
