// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `consume_staged_covers`, `cover_budget_key`, `cover_cache_paths`, `cover_error`, `cover_fetch_enabled_from_conn`, `cover_job_failure_state`, `cover_source_fingerprint`, `cover_source_info`, `cover_workers`, `current_cover_fetch_enabled`, `durable_cover_progress_on`, `effective_scan_mode`, `error_code`, `fetch_remote_cover_image_with_dimensions`, `initial_scan_path`, `job_dto`, `jobs`, `next_job_id`, `parse_bool_setting`, `parse_cover_profile`, `parse_cover_selection`, `parse_initial_listing`, `persist_config_status`, `persist_terminal`, `refresh_cover_progress`, `refresh_status_counts`, `run_remote_cover_worker`, `start_job`, `start_lock`, `storage_failed`, `wake_remote_cover_worker`, `write_remote_cover_cache`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AdapterByteSource`, `CoverConsumeResult`, `CoverSourceInfo`, `InitialListingEntry`, `ScanJob`, `SqliteScanSink`, `StartConfig`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `enqueue_cover`, `previous_fingerprint`, `should_recheck_directory`, `spill_directory`, `stage_directory`, `take_spilled_directory`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`, `len`, `read_at`

Future<RemoteScanJobDto> remoteScanStart({
  required String sourceType,
  required String sourceId,
  required BigInt session,
  required String rootPath,
  required String mode,
  String? initialListingJson,
}) => RustLib.instance.api.crateApiRemoteScanRemoteScanStart(
  sourceType: sourceType,
  sourceId: sourceId,
  session: session,
  rootPath: rootPath,
  mode: mode,
  initialListingJson: initialListingJson,
);

/// Start a user-requested scan. Manual incremental scans intentionally bypass
/// the automatic 15-minute directory TTL once, while the ordinary start API
/// retains the inexpensive automatic recheck behavior.
Future<RemoteScanJobDto> remoteScanStartManual({
  required String sourceType,
  required String sourceId,
  required BigInt session,
  required String rootPath,
  required String mode,
  String? initialListingJson,
}) => RustLib.instance.api.crateApiRemoteScanRemoteScanStartManual(
  sourceType: sourceType,
  sourceId: sourceId,
  session: session,
  rootPath: rootPath,
  mode: mode,
  initialListingJson: initialListingJson,
);

Future<RemoteScanStatusDto?> remoteScanStatus({required String sourceId}) =>
    RustLib.instance.api.crateApiRemoteScanRemoteScanStatus(sourceId: sourceId);

Future<void> remoteScanPause({required String sourceId}) =>
    RustLib.instance.api.crateApiRemoteScanRemoteScanPause(sourceId: sourceId);

Future<void> remoteScanResume({required String sourceId}) =>
    RustLib.instance.api.crateApiRemoteScanRemoteScanResume(sourceId: sourceId);

Future<void> remoteScanCancel({required String sourceId}) =>
    RustLib.instance.api.crateApiRemoteScanRemoteScanCancel(sourceId: sourceId);

class RemoteScanJobDto {
  final String jobId;
  final String sourceId;
  final String status;
  final String mode;
  final PlatformInt64 generation;

  const RemoteScanJobDto({
    required this.jobId,
    required this.sourceId,
    required this.status,
    required this.mode,
    required this.generation,
  });

  @override
  int get hashCode =>
      jobId.hashCode ^
      sourceId.hashCode ^
      status.hashCode ^
      mode.hashCode ^
      generation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RemoteScanJobDto &&
          runtimeType == other.runtimeType &&
          jobId == other.jobId &&
          sourceId == other.sourceId &&
          status == other.status &&
          mode == other.mode &&
          generation == other.generation;
}

class RemoteScanStatusDto {
  final String sourceId;
  final String status;
  final String mode;
  final PlatformInt64 generation;
  final String? checkpoint;
  final PlatformInt64? lastSuccessAt;
  final String? errorCode;
  final BigInt processed;
  final BigInt total;

  /// Directory discovery phase is intentionally separate from cover
  /// readiness.  `processed/total` remain for old clients only.
  final String listingPhase;
  final BigInt directoriesChecked;
  final BigInt discoveredBooks;
  final bool discoveryComplete;
  final BigInt readyBooks;
  final BigInt activeBooks;
  final BigInt pendingBooks;
  final BigInt retryBooks;
  final BigInt blockedBooks;
  final BigInt unsupportedBooks;
  final BigInt failedBooks;
  final PlatformInt64 viewRevision;

  const RemoteScanStatusDto({
    required this.sourceId,
    required this.status,
    required this.mode,
    required this.generation,
    this.checkpoint,
    this.lastSuccessAt,
    this.errorCode,
    required this.processed,
    required this.total,
    required this.listingPhase,
    required this.directoriesChecked,
    required this.discoveredBooks,
    required this.discoveryComplete,
    required this.readyBooks,
    required this.activeBooks,
    required this.pendingBooks,
    required this.retryBooks,
    required this.blockedBooks,
    required this.unsupportedBooks,
    required this.failedBooks,
    required this.viewRevision,
  });

  @override
  int get hashCode =>
      sourceId.hashCode ^
      status.hashCode ^
      mode.hashCode ^
      generation.hashCode ^
      checkpoint.hashCode ^
      lastSuccessAt.hashCode ^
      errorCode.hashCode ^
      processed.hashCode ^
      total.hashCode ^
      listingPhase.hashCode ^
      directoriesChecked.hashCode ^
      discoveredBooks.hashCode ^
      discoveryComplete.hashCode ^
      readyBooks.hashCode ^
      activeBooks.hashCode ^
      pendingBooks.hashCode ^
      retryBooks.hashCode ^
      blockedBooks.hashCode ^
      unsupportedBooks.hashCode ^
      failedBooks.hashCode ^
      viewRevision.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RemoteScanStatusDto &&
          runtimeType == other.runtimeType &&
          sourceId == other.sourceId &&
          status == other.status &&
          mode == other.mode &&
          generation == other.generation &&
          checkpoint == other.checkpoint &&
          lastSuccessAt == other.lastSuccessAt &&
          errorCode == other.errorCode &&
          processed == other.processed &&
          total == other.total &&
          listingPhase == other.listingPhase &&
          directoriesChecked == other.directoriesChecked &&
          discoveredBooks == other.discoveredBooks &&
          discoveryComplete == other.discoveryComplete &&
          readyBooks == other.readyBooks &&
          activeBooks == other.activeBooks &&
          pendingBooks == other.pendingBooks &&
          retryBooks == other.retryBooks &&
          blockedBooks == other.blockedBooks &&
          unsupportedBooks == other.unsupportedBooks &&
          failedBooks == other.failedBooks &&
          viewRevision == other.viewRevision;
}
