// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `consume_staged_covers`, `cover_budget_key`, `cover_cache_paths`, `cover_error_worth_escalating`, `cover_fetch_enabled_from_conn`, `cover_image_dimensions`, `cover_job_failure_decision`, `cover_job_failure_state`, `cover_open_reason`, `cover_page_scan_limit`, `cover_quality_profile_on`, `cover_read_windows`, `cover_reason`, `cover_route_for_job`, `cover_source_fingerprint`, `cover_source_info`, `cover_top_band_crop`, `cover_workers`, `current_cover_fetch_enabled`, `decode_cover_bounded`, `decode_first_usable_page`, `durable_cover_progress_on`, `effective_scan_mode`, `error_code`, `fetch_cover_by_windows`, `fetch_cover_from_document`, `fetch_remote_cover_image_with_dimensions`, `initial_scan_path`, `job_dto`, `jobs`, `long_retry_is_retryable`, `new`, `next_job_id`, `parse_bool_setting`, `parse_cover_profile`, `parse_cover_selection`, `parse_initial_listing`, `persist_config_status`, `persist_terminal`, `provider_failure_code`, `refresh_cover_progress`, `refresh_status_counts`, `run_remote_cover_worker`, `safe_malformed_code`, `span`, `start_job`, `start_lock`, `storage_failed`, `wake_cover_worker_for_source`, `wake_cover_worker`, `wake_remote_cover_worker`, `with_budget`, `write_remote_cover_cache`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AdapterByteSource`, `CoverConsumeResult`, `CoverFailureDecision`, `CoverFetchTrace`, `CoverSourceInfo`, `InitialListingEntry`, `ScanJob`, `SqliteScanSink`, `StartConfig`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `enqueue_cover`, `previous_fingerprint`, `should_recheck_directory`, `spill_directory`, `stage_directory`, `take_spilled_directory`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`, `len`, `read_at`

/// **source-session lifecycle 事实通知**（P1-C）。
///
/// Dart 只报告一个它本来就掌握的事实：某个 source 已成功获得/更新为当前有效 session。
/// Dart **不**查 failed job、**不**算 6 小时、**不**改 retry state、**不**决定
/// unsupported/blocked、**不**决定 worker 是否启动 —— 这些全部由 Rust 拥有。
///
/// Rust 侧职责：
/// 1. 验证该 source/session 关系（source 必须存在）；
/// 2. 复用既有可信路径 `rebind_completed_generation_session`，让已完成的 generation
///    绑定到当前有效 session；
/// 3. 验证现在确实存在该 session 的绑定；**取不到就什么都不做**（不猜、不伪造）；
/// 4. 对该 source 执行 **bounded、source-scoped** 的 reconciliation；
/// 5. 如产生 claimable work，复用 P1-B 的 `wake_cover_worker_for_source`。
///
/// 幂等：重复通知不会重复生成 job、不会重复消耗长期补偿、不会重复 spawn consumer。
/// 本函数自身**不做任何 provider 网络请求**。
Future<RemoteCoverReconcileDto> notifySourceSessionReady({
  required String sourceId,
  required BigInt session,
}) => RustLib.instance.api.crateApiRemoteScanNotifySourceSessionReady(
  sourceId: sourceId,
  session: session,
);

Future<RemoteScanJobDto> remoteScanStart({
  required String sourceType,
  required String sourceId,
  required BigInt session,
  required String rootPath,
  required String mode,
  String? initialListingJson,
}) => RustLib.instance.api.crateApiRemoteScanRemoteScanStart(
  sourceType: sourceType,
  sourceId: sourceId,
  session: session,
  rootPath: rootPath,
  mode: mode,
  initialListingJson: initialListingJson,
);

/// Start a user-requested scan. Manual incremental scans intentionally bypass
/// the automatic 15-minute directory TTL once, while the ordinary start API
/// retains the inexpensive automatic recheck behavior.
Future<RemoteScanJobDto> remoteScanStartManual({
  required String sourceType,
  required String sourceId,
  required BigInt session,
  required String rootPath,
  required String mode,
  String? initialListingJson,
}) => RustLib.instance.api.crateApiRemoteScanRemoteScanStartManual(
  sourceType: sourceType,
  sourceId: sourceId,
  session: session,
  rootPath: rootPath,
  mode: mode,
  initialListingJson: initialListingJson,
);

/// RG-B 健壮性修复（A）：应用启动时调用一次 —— 把崩溃/强制退出留下的 `running` 扫描残留
/// 恢复为**中断终态**，使这些源能重新扫描（否则后续 epoch/baseline 证明会永久拒绝启动）。
///
/// 返回被恢复的源数量（0 = 无残留）。启动时内存 job 表为空，因此该操作是安全的；
/// **运行期不要调用**（会把正在进行的扫描误标为中断）。
Future<int> remoteScanRecoverInterruptedAll() =>
    RustLib.instance.api.crateApiRemoteScanRemoteScanRecoverInterruptedAll();

Future<RemoteScanStatusDto?> remoteScanStatus({required String sourceId}) =>
    RustLib.instance.api.crateApiRemoteScanRemoteScanStatus(sourceId: sourceId);

Future<void> remoteScanPause({required String sourceId}) =>
    RustLib.instance.api.crateApiRemoteScanRemoteScanPause(sourceId: sourceId);

Future<void> remoteScanResume({required String sourceId}) =>
    RustLib.instance.api.crateApiRemoteScanRemoteScanResume(sourceId: sourceId);

Future<void> remoteScanCancel({required String sourceId}) =>
    RustLib.instance.api.crateApiRemoteScanRemoteScanCancel(sourceId: sourceId);

/// `notify_source_session_ready` 的返回：只描述本次 reconciliation 做了什么。
class RemoteCoverReconcileDto {
  /// 该 source 当前是否存在可信的 source/session 绑定。false 表示本次什么都没做。
  final bool bindingAvailable;

  /// 被推进为可 claim 的长期补偿 job 数。
  final int compensationPromoted;

  /// 因 auth/session blocker 解除而回到候选队列的 job 数。
  final int blockerCleared;

  /// 因 library 缺口而新建的 pending job 数。
  final int jobsCreated;

  /// 本次是否产生了可 claim 的工作（Rust 侧据此已复用 P1-B 的 worker wake）。
  final bool claimable;

  /// 是否因预算上限提前结束（剩余工作留给后续 session 事件）。
  final bool truncated;

  const RemoteCoverReconcileDto({
    required this.bindingAvailable,
    required this.compensationPromoted,
    required this.blockerCleared,
    required this.jobsCreated,
    required this.claimable,
    required this.truncated,
  });

  static Future<RemoteCoverReconcileDto> default_() =>
      RustLib.instance.api.crateApiRemoteScanRemoteCoverReconcileDtoDefault();

  @override
  int get hashCode =>
      bindingAvailable.hashCode ^
      compensationPromoted.hashCode ^
      blockerCleared.hashCode ^
      jobsCreated.hashCode ^
      claimable.hashCode ^
      truncated.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RemoteCoverReconcileDto &&
          runtimeType == other.runtimeType &&
          bindingAvailable == other.bindingAvailable &&
          compensationPromoted == other.compensationPromoted &&
          blockerCleared == other.blockerCleared &&
          jobsCreated == other.jobsCreated &&
          claimable == other.claimable &&
          truncated == other.truncated;
}

class RemoteScanJobDto {
  final String jobId;
  final String sourceId;
  final String status;
  final String mode;
  final PlatformInt64 generation;

  const RemoteScanJobDto({
    required this.jobId,
    required this.sourceId,
    required this.status,
    required this.mode,
    required this.generation,
  });

  @override
  int get hashCode =>
      jobId.hashCode ^
      sourceId.hashCode ^
      status.hashCode ^
      mode.hashCode ^
      generation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RemoteScanJobDto &&
          runtimeType == other.runtimeType &&
          jobId == other.jobId &&
          sourceId == other.sourceId &&
          status == other.status &&
          mode == other.mode &&
          generation == other.generation;
}

class RemoteScanStatusDto {
  final String sourceId;
  final String status;
  final String mode;
  final PlatformInt64 generation;
  final String? checkpoint;
  final PlatformInt64? lastSuccessAt;
  final String? errorCode;
  final BigInt processed;
  final BigInt total;

  /// Directory discovery phase is intentionally separate from cover
  /// readiness.  `processed/total` remain for old clients only.
  final String listingPhase;
  final BigInt directoriesChecked;
  final BigInt discoveredBooks;
  final bool discoveryComplete;
  final BigInt readyBooks;
  final BigInt activeBooks;
  final BigInt pendingBooks;
  final BigInt retryBooks;
  final BigInt blockedBooks;
  final BigInt unsupportedBooks;
  final BigInt failedBooks;

  /// P1-F：`ready` **且字节真的可用**的漫画数（缓存/文件系统校验，锁外计算）。
  final BigInt availableBooks;

  /// P1-F：等待中的漫画数 = pending + retry + stale-ready + no-job。
  final BigInt waitingBooks;

  /// P1-F：真实未知 durable state 的漫画数（默认 0；不变量违例也会在此显式暴露）。
  final BigInt otherBooks;
  final PlatformInt64 viewRevision;

  const RemoteScanStatusDto({
    required this.sourceId,
    required this.status,
    required this.mode,
    required this.generation,
    this.checkpoint,
    this.lastSuccessAt,
    this.errorCode,
    required this.processed,
    required this.total,
    required this.listingPhase,
    required this.directoriesChecked,
    required this.discoveredBooks,
    required this.discoveryComplete,
    required this.readyBooks,
    required this.activeBooks,
    required this.pendingBooks,
    required this.retryBooks,
    required this.blockedBooks,
    required this.unsupportedBooks,
    required this.failedBooks,
    required this.availableBooks,
    required this.waitingBooks,
    required this.otherBooks,
    required this.viewRevision,
  });

  @override
  int get hashCode =>
      sourceId.hashCode ^
      status.hashCode ^
      mode.hashCode ^
      generation.hashCode ^
      checkpoint.hashCode ^
      lastSuccessAt.hashCode ^
      errorCode.hashCode ^
      processed.hashCode ^
      total.hashCode ^
      listingPhase.hashCode ^
      directoriesChecked.hashCode ^
      discoveredBooks.hashCode ^
      discoveryComplete.hashCode ^
      readyBooks.hashCode ^
      activeBooks.hashCode ^
      pendingBooks.hashCode ^
      retryBooks.hashCode ^
      blockedBooks.hashCode ^
      unsupportedBooks.hashCode ^
      failedBooks.hashCode ^
      availableBooks.hashCode ^
      waitingBooks.hashCode ^
      otherBooks.hashCode ^
      viewRevision.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RemoteScanStatusDto &&
          runtimeType == other.runtimeType &&
          sourceId == other.sourceId &&
          status == other.status &&
          mode == other.mode &&
          generation == other.generation &&
          checkpoint == other.checkpoint &&
          lastSuccessAt == other.lastSuccessAt &&
          errorCode == other.errorCode &&
          processed == other.processed &&
          total == other.total &&
          listingPhase == other.listingPhase &&
          directoriesChecked == other.directoriesChecked &&
          discoveredBooks == other.discoveredBooks &&
          discoveryComplete == other.discoveryComplete &&
          readyBooks == other.readyBooks &&
          activeBooks == other.activeBooks &&
          pendingBooks == other.pendingBooks &&
          retryBooks == other.retryBooks &&
          blockedBooks == other.blockedBooks &&
          unsupportedBooks == other.unsupportedBooks &&
          failedBooks == other.failedBooks &&
          availableBooks == other.availableBooks &&
          waitingBooks == other.waitingBooks &&
          otherBooks == other.otherBooks &&
          viewRevision == other.viewRevision;
}
