// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'book.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `cover_dto`, `kind_name`, `profile_key`, `route_revision_on`, `route_session_matches_on`, `selection_key`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `RouteRevision`

Future<RemoteDirectoryViewDto> remoteDirectoryView({
  required String sourceId,
  required String logicalPath,
  required int offset,
  required int limit,
}) => RustLib.instance.api.crateApiRemoteCoverRemoteDirectoryView(
  sourceId: sourceId,
  logicalPath: logicalPath,
  offset: offset,
  limit: limit,
);

Future<RemoteCoverStateDto> remoteCoverRequest({
  required String sourceId,
  required BigInt session,
  required String assetId,
  required String consumerId,
  required CoverSelectionDto selection,
  required CoverProfileDto profile,
}) => RustLib.instance.api.crateApiRemoteCoverRemoteCoverRequest(
  sourceId: sourceId,
  session: session,
  assetId: assetId,
  consumerId: consumerId,
  selection: selection,
  profile: profile,
);

Future<PageImage?> remoteCoverRead({
  required String sourceId,
  required String assetId,
  required CoverSelectionDto selection,
  required CoverProfileDto profile,
}) => RustLib.instance.api.crateApiRemoteCoverRemoteCoverRead(
  sourceId: sourceId,
  assetId: assetId,
  selection: selection,
  profile: profile,
);

Future<void> remoteCoverRelease({required String consumerId}) => RustLib
    .instance
    .api
    .crateApiRemoteCoverRemoteCoverRelease(consumerId: consumerId);

Future<void> remoteCoverRetry({
  required String sourceId,
  required BigInt session,
  required List<String> assetIds,
}) => RustLib.instance.api.crateApiRemoteCoverRemoteCoverRetry(
  sourceId: sourceId,
  session: session,
  assetIds: assetIds,
);

/// P1-E：Dart coordinator 订阅 cover revision wake-up。
///
/// **单 subscriber**：再次调用**替换**当前 sink（resubscribe），不做 broadcast
/// registry；send 失败只清掉失效 sink，不影响 worker / durable state。
/// 传输是 best-effort，且事件只在 durable mutation **提交成功之后**发出。
Stream<CoverRevisionEvent> subscribeCoverRevisions() =>
    RustLib.instance.api.crateApiRemoteCoverSubscribeCoverRevisions();

/// P1-E：**只读**读取某 asset 当前的 durable cover state。
///
/// 契约（硬）：
/// * read only —— **不** enqueue、**不** wake、**不** 建 session、**不** 访问 provider、
///   **不** 修改任何 durable state，也**不** bump revision；
/// * 直接复用内部 `catalog::cover_state_for` 与既有 `cover_dto`，不另建平行状态 enum；
/// * `Ok(None)` 表示该 asset **没有**任何 job/variant 记录（UI 语义 = "no job"）。
///
/// 这是 UI 消费 durable truth 的唯一读入口 —— 禁止用 `remote_cover_request`（它会 enqueue）
/// 代替本函数。
///
/// **第 79 轮续（真机 bug 修复）**：必须传入调用方**实际使用**的 `selection` + `profile`。
/// 曾经这里读的是写死的 `default` / `340x480@1`，而卡片按 `coverQuality` 请求
/// `170x240@1` ⇒ 图已 ready 但墙面仍按另一 profile 的旧 `failed` 显示"获取失败"。
Future<RemoteCoverStateDto?> remoteCoverState({
  required String sourceId,
  required String assetId,
  required CoverSelectionDto selection,
  required CoverProfileDto profile,
}) => RustLib.instance.api.crateApiRemoteCoverRemoteCoverState(
  sourceId: sourceId,
  assetId: assetId,
  selection: selection,
  profile: profile,
);

Future<PlatformInt64> remoteViewRevision({required String sourceId}) => RustLib
    .instance
    .api
    .crateApiRemoteCoverRemoteViewRevision(sourceId: sourceId);

/// 第 80 轮：把封面缓存**重置到当前 `coverQuality` 档位**，并让终态失败重新有机会。
///
/// 为什么需要（有真机/桌面数据支撑）：
/// 1. **抓错档**：扫描过去固定抓 340×480，而卡片按设置取图（低 = 170×240）⇒ 实测
///    「金牌得主」目录 340 档 ready 15 本、170 档只有 15 本而另一批 11 本是预算失败；
/// 2. **终态失败不会自愈**：`attempt>=3` 判永久失败（`next_attempt_at=0`、无 6h 补偿），
///    用户库里 `1.pdf`–`7.pdf`（attempt 4–5）与 8 个 MOBI 都卡死在这种状态 ——
///    清掉它们重新排队，是让"改过上限/修过 bug"之后的重新尝试真正生效的唯一路径。
///
/// 做四件事（幂等，只动**封面**数据，不碰书架索引）：
/// 1. 删除非当前档的 `remote_cover_job` / `remote_cover_variant` 行；
/// 2. 删除不再被任何变体或引用指向的 `remote_cover_blob` 行，并删除其磁盘文件；
/// 3. 把当前档里 **`state='failed'`** 的任务重新排队（`attempt=0`、清错误码与租约）；
///    `blocked`（需重新登录）与 `unsupported`（格式本身给不出封面）保持原样 —— 重试无意义；
/// 4. bump 各源封面 revision，界面据此重新读 durable state。
Future<RemoteCoverResetDto> remoteCoverResetToCurrentProfile() =>
    RustLib.instance.api.crateApiRemoteCoverRemoteCoverResetToCurrentProfile();

class CoverProfileDto {
  final int width;
  final int height;
  final int decoderVersion;

  const CoverProfileDto({
    required this.width,
    required this.height,
    required this.decoderVersion,
  });

  @override
  int get hashCode =>
      width.hashCode ^ height.hashCode ^ decoderVersion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoverProfileDto &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          decoderVersion == other.decoderVersion;
}

/// P1-E：cover durable truth 可能变化的**事实**。
///
/// 刻意**不含** authoritative 状态：没有 state / error_code / retry 信息 /
/// authoritative revision；consumer 收到后必须自己重读 durable state。
class CoverRevisionEvent {
  /// 发生变化的 source。
  final String sourceId;

  /// transition 天然知道时才带；无法确定唯一 asset（例如一次 compensation
  /// batch 改了多本）时为 None，由 Dart 让该 source 的 mounted cards 各自 reread。
  final String? assetId;

  const CoverRevisionEvent({required this.sourceId, this.assetId});

  @override
  int get hashCode => sourceId.hashCode ^ assetId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoverRevisionEvent &&
          runtimeType == other.runtimeType &&
          sourceId == other.sourceId &&
          assetId == other.assetId;
}

class CoverSelectionDto {
  final int page;
  final CropRect? crop;
  final String? explicitAssetId;
  final String revision;

  const CoverSelectionDto({
    required this.page,
    this.crop,
    this.explicitAssetId,
    required this.revision,
  });

  @override
  int get hashCode =>
      page.hashCode ^
      crop.hashCode ^
      explicitAssetId.hashCode ^
      revision.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoverSelectionDto &&
          runtimeType == other.runtimeType &&
          page == other.page &&
          crop == other.crop &&
          explicitAssetId == other.explicitAssetId &&
          revision == other.revision;
}

/// 第 80 轮：封面缓存"重置到当前档位"的结果摘要（供界面提示与测试断言）。
class RemoteCoverResetDto {
  /// 被删除的、**非当前档位**的变体行数。
  final int purgedVariants;

  /// 被删除的、**非当前档位**的任务行数。
  final int purgedJobs;

  /// 被删除的孤儿 blob 行数（及其磁盘文件）。
  final int purgedBlobs;

  /// 重新排队（attempt 归零）的终态失败任务数。
  final int requeuedJobs;

  /// 被 bump 封面 revision 的源数量。
  final int sources;

  /// 生效的档位（便于界面显示"已切到 340x480@1"）。
  final String profile;

  const RemoteCoverResetDto({
    required this.purgedVariants,
    required this.purgedJobs,
    required this.purgedBlobs,
    required this.requeuedJobs,
    required this.sources,
    required this.profile,
  });

  @override
  int get hashCode =>
      purgedVariants.hashCode ^
      purgedJobs.hashCode ^
      purgedBlobs.hashCode ^
      requeuedJobs.hashCode ^
      sources.hashCode ^
      profile.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RemoteCoverResetDto &&
          runtimeType == other.runtimeType &&
          purgedVariants == other.purgedVariants &&
          purgedJobs == other.purgedJobs &&
          purgedBlobs == other.purgedBlobs &&
          requeuedJobs == other.requeuedJobs &&
          sources == other.sources &&
          profile == other.profile;
}

class RemoteCoverStateDto {
  final String state;
  final PlatformInt64 revision;
  final bool ready;
  final String? errorCode;
  final PlatformInt64? retryAt;
  final bool isPreviousRevision;

  const RemoteCoverStateDto({
    required this.state,
    required this.revision,
    required this.ready,
    this.errorCode,
    this.retryAt,
    required this.isPreviousRevision,
  });

  @override
  int get hashCode =>
      state.hashCode ^
      revision.hashCode ^
      ready.hashCode ^
      errorCode.hashCode ^
      retryAt.hashCode ^
      isPreviousRevision.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RemoteCoverStateDto &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          revision == other.revision &&
          ready == other.ready &&
          errorCode == other.errorCode &&
          retryAt == other.retryAt &&
          isPreviousRevision == other.isPreviousRevision;
}

class RemoteDirectoryEntryDto {
  final String assetId;
  final String logicalPath;
  final String? providerPath;
  final String name;
  final String assetKind;
  final BigInt? size;
  final String? representativeAssetId;
  final RemoteCoverStateDto cover;

  const RemoteDirectoryEntryDto({
    required this.assetId,
    required this.logicalPath,
    this.providerPath,
    required this.name,
    required this.assetKind,
    this.size,
    this.representativeAssetId,
    required this.cover,
  });

  @override
  int get hashCode =>
      assetId.hashCode ^
      logicalPath.hashCode ^
      providerPath.hashCode ^
      name.hashCode ^
      assetKind.hashCode ^
      size.hashCode ^
      representativeAssetId.hashCode ^
      cover.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RemoteDirectoryEntryDto &&
          runtimeType == other.runtimeType &&
          assetId == other.assetId &&
          logicalPath == other.logicalPath &&
          providerPath == other.providerPath &&
          name == other.name &&
          assetKind == other.assetKind &&
          size == other.size &&
          representativeAssetId == other.representativeAssetId &&
          cover == other.cover;
}

class RemoteDirectoryViewDto {
  final String sourceId;
  final String logicalPath;
  final PlatformInt64 revision;
  final bool listingComplete;
  final bool hasMore;
  final List<RemoteDirectoryEntryDto> entries;

  const RemoteDirectoryViewDto({
    required this.sourceId,
    required this.logicalPath,
    required this.revision,
    required this.listingComplete,
    required this.hasMore,
    required this.entries,
  });

  @override
  int get hashCode =>
      sourceId.hashCode ^
      logicalPath.hashCode ^
      revision.hashCode ^
      listingComplete.hashCode ^
      hasMore.hashCode ^
      entries.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RemoteDirectoryViewDto &&
          runtimeType == other.runtimeType &&
          sourceId == other.sourceId &&
          logicalPath == other.logicalPath &&
          revision == other.revision &&
          listingComplete == other.listingComplete &&
          hasMore == other.hasMore &&
          entries == other.entries;
}
