// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'book.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `cover_dto`, `kind_name`, `profile_key`, `route_revision_on`, `selection_key`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `RouteRevision`

Future<RemoteDirectoryViewDto> remoteDirectoryView({
  required String sourceId,
  required String logicalPath,
  required int offset,
  required int limit,
}) => RustLib.instance.api.crateApiRemoteCoverRemoteDirectoryView(
  sourceId: sourceId,
  logicalPath: logicalPath,
  offset: offset,
  limit: limit,
);

Future<RemoteCoverStateDto> remoteCoverRequest({
  required String sourceId,
  required BigInt session,
  required String assetId,
  required String consumerId,
  required CoverSelectionDto selection,
  required CoverProfileDto profile,
}) => RustLib.instance.api.crateApiRemoteCoverRemoteCoverRequest(
  sourceId: sourceId,
  session: session,
  assetId: assetId,
  consumerId: consumerId,
  selection: selection,
  profile: profile,
);

Future<PageImage?> remoteCoverRead({
  required String sourceId,
  required String assetId,
  required CoverSelectionDto selection,
  required CoverProfileDto profile,
}) => RustLib.instance.api.crateApiRemoteCoverRemoteCoverRead(
  sourceId: sourceId,
  assetId: assetId,
  selection: selection,
  profile: profile,
);

Future<void> remoteCoverRelease({required String consumerId}) => RustLib
    .instance
    .api
    .crateApiRemoteCoverRemoteCoverRelease(consumerId: consumerId);

Future<void> remoteCoverRetry({
  required String sourceId,
  required BigInt session,
  required List<String> assetIds,
}) => RustLib.instance.api.crateApiRemoteCoverRemoteCoverRetry(
  sourceId: sourceId,
  session: session,
  assetIds: assetIds,
);

Future<PlatformInt64> remoteViewRevision({required String sourceId}) => RustLib
    .instance
    .api
    .crateApiRemoteCoverRemoteViewRevision(sourceId: sourceId);

class CoverProfileDto {
  final int width;
  final int height;
  final int decoderVersion;

  const CoverProfileDto({
    required this.width,
    required this.height,
    required this.decoderVersion,
  });

  @override
  int get hashCode =>
      width.hashCode ^ height.hashCode ^ decoderVersion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoverProfileDto &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          decoderVersion == other.decoderVersion;
}

class CoverSelectionDto {
  final int page;
  final CropRect? crop;
  final String? explicitAssetId;
  final String revision;

  const CoverSelectionDto({
    required this.page,
    this.crop,
    this.explicitAssetId,
    required this.revision,
  });

  @override
  int get hashCode =>
      page.hashCode ^
      crop.hashCode ^
      explicitAssetId.hashCode ^
      revision.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoverSelectionDto &&
          runtimeType == other.runtimeType &&
          page == other.page &&
          crop == other.crop &&
          explicitAssetId == other.explicitAssetId &&
          revision == other.revision;
}

class RemoteCoverStateDto {
  final String state;
  final PlatformInt64 revision;
  final bool ready;
  final String? errorCode;
  final PlatformInt64? retryAt;
  final bool isPreviousRevision;

  const RemoteCoverStateDto({
    required this.state,
    required this.revision,
    required this.ready,
    this.errorCode,
    this.retryAt,
    required this.isPreviousRevision,
  });

  @override
  int get hashCode =>
      state.hashCode ^
      revision.hashCode ^
      ready.hashCode ^
      errorCode.hashCode ^
      retryAt.hashCode ^
      isPreviousRevision.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RemoteCoverStateDto &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          revision == other.revision &&
          ready == other.ready &&
          errorCode == other.errorCode &&
          retryAt == other.retryAt &&
          isPreviousRevision == other.isPreviousRevision;
}

class RemoteDirectoryEntryDto {
  final String assetId;
  final String logicalPath;
  final String? providerPath;
  final String name;
  final String assetKind;
  final BigInt? size;
  final String? representativeAssetId;
  final RemoteCoverStateDto cover;

  const RemoteDirectoryEntryDto({
    required this.assetId,
    required this.logicalPath,
    this.providerPath,
    required this.name,
    required this.assetKind,
    this.size,
    this.representativeAssetId,
    required this.cover,
  });

  @override
  int get hashCode =>
      assetId.hashCode ^
      logicalPath.hashCode ^
      providerPath.hashCode ^
      name.hashCode ^
      assetKind.hashCode ^
      size.hashCode ^
      representativeAssetId.hashCode ^
      cover.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RemoteDirectoryEntryDto &&
          runtimeType == other.runtimeType &&
          assetId == other.assetId &&
          logicalPath == other.logicalPath &&
          providerPath == other.providerPath &&
          name == other.name &&
          assetKind == other.assetKind &&
          size == other.size &&
          representativeAssetId == other.representativeAssetId &&
          cover == other.cover;
}

class RemoteDirectoryViewDto {
  final String sourceId;
  final String logicalPath;
  final PlatformInt64 revision;
  final bool listingComplete;
  final bool hasMore;
  final List<RemoteDirectoryEntryDto> entries;

  const RemoteDirectoryViewDto({
    required this.sourceId,
    required this.logicalPath,
    required this.revision,
    required this.listingComplete,
    required this.hasMore,
    required this.entries,
  });

  @override
  int get hashCode =>
      sourceId.hashCode ^
      logicalPath.hashCode ^
      revision.hashCode ^
      listingComplete.hashCode ^
      hasMore.hashCode ^
      entries.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RemoteDirectoryViewDto &&
          runtimeType == other.runtimeType &&
          sourceId == other.sourceId &&
          logicalPath == other.logicalPath &&
          revision == other.revision &&
          listingComplete == other.listingComplete &&
          hasMore == other.hasMore &&
          entries == other.entries;
}
