// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `consume_staged_covers`, `error_code`, `fetch_safe_cover_partial`, `job_dto`, `jobs`, `next_job_id`, `persist_config_status`, `persist_terminal`, `start_job`, `start_lock`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ScanJob`, `SqliteScanSink`, `StartConfig`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `enqueue_cover`, `previous_fingerprint`, `spill_directory`, `stage_directory`, `take_spilled_directory`

Future<RemoteScanJobDto> remoteScanStart({
  required String sourceType,
  required String sourceId,
  required BigInt session,
  required String rootPath,
  required String mode,
}) => RustLib.instance.api.crateApiRemoteScanRemoteScanStart(
  sourceType: sourceType,
  sourceId: sourceId,
  session: session,
  rootPath: rootPath,
  mode: mode,
);

Future<RemoteScanStatusDto?> remoteScanStatus({required String sourceId}) =>
    RustLib.instance.api.crateApiRemoteScanRemoteScanStatus(sourceId: sourceId);

Future<void> remoteScanPause({required String sourceId}) =>
    RustLib.instance.api.crateApiRemoteScanRemoteScanPause(sourceId: sourceId);

Future<void> remoteScanResume({required String sourceId}) =>
    RustLib.instance.api.crateApiRemoteScanRemoteScanResume(sourceId: sourceId);

Future<void> remoteScanCancel({required String sourceId}) =>
    RustLib.instance.api.crateApiRemoteScanRemoteScanCancel(sourceId: sourceId);

class RemoteScanJobDto {
  final String jobId;
  final String sourceId;
  final String status;
  final String mode;
  final PlatformInt64 generation;

  const RemoteScanJobDto({
    required this.jobId,
    required this.sourceId,
    required this.status,
    required this.mode,
    required this.generation,
  });

  @override
  int get hashCode =>
      jobId.hashCode ^
      sourceId.hashCode ^
      status.hashCode ^
      mode.hashCode ^
      generation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RemoteScanJobDto &&
          runtimeType == other.runtimeType &&
          jobId == other.jobId &&
          sourceId == other.sourceId &&
          status == other.status &&
          mode == other.mode &&
          generation == other.generation;
}

class RemoteScanStatusDto {
  final String sourceId;
  final String status;
  final String mode;
  final PlatformInt64 generation;
  final String? checkpoint;
  final PlatformInt64? lastSuccessAt;
  final String? errorCode;
  final BigInt processed;
  final BigInt total;

  const RemoteScanStatusDto({
    required this.sourceId,
    required this.status,
    required this.mode,
    required this.generation,
    this.checkpoint,
    this.lastSuccessAt,
    this.errorCode,
    required this.processed,
    required this.total,
  });

  @override
  int get hashCode =>
      sourceId.hashCode ^
      status.hashCode ^
      mode.hashCode ^
      generation.hashCode ^
      checkpoint.hashCode ^
      lastSuccessAt.hashCode ^
      errorCode.hashCode ^
      processed.hashCode ^
      total.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RemoteScanStatusDto &&
          runtimeType == other.runtimeType &&
          sourceId == other.sourceId &&
          status == other.status &&
          mode == other.mode &&
          generation == other.generation &&
          checkpoint == other.checkpoint &&
          lastSuccessAt == other.lastSuccessAt &&
          errorCode == other.errorCode &&
          processed == other.processed &&
          total == other.total;
}
