// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../scrape_projection.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `depth`, `input_revision_from_snapshot`, `input_revision`, `proposal_dto`, `proposal_row_dto`, `proposal_row`, `queue_dto`, `run_catalog_pass`, `run_dto`, `state_name`

Future<ScrapeProposalDto> dbParseCatalog({
  required String bookKey,
  required String filename,
  required List<String> ancestorDirs,
  required PlatformInt64 ancestorDepth,
  required String ruleVersion,
}) => RustLib.instance.api.crateApiScraperDbParseCatalog(
  bookKey: bookKey,
  filename: filename,
  ancestorDirs: ancestorDirs,
  ancestorDepth: ancestorDepth,
  ruleVersion: ruleVersion,
);

/// Run one persisted catalog-only scrape pass. The caller may invoke this
/// after sync, from a timer, or from the review screen; all paths are local.
Future<ScrapeRunDto> dbRunCatalogScrape({
  required String trigger,
  required PlatformInt64 ancestorDepth,
  required String ruleVersion,
}) => RustLib.instance.api.crateApiScraperDbRunCatalogScrape(
  trigger: trigger,
  ancestorDepth: ancestorDepth,
  ruleVersion: ruleVersion,
);

Future<List<ScrapeProposalDto>> dbLoadScrapeProposals({
  required PlatformInt64 limit,
  required String state,
}) => RustLib.instance.api.crateApiScraperDbLoadScrapeProposals(
  limit: limit,
  state: state,
);

Future<List<ScrapeRunDto>> dbLoadScrapeJobs({required PlatformInt64 limit}) =>
    RustLib.instance.api.crateApiScraperDbLoadScrapeJobs(limit: limit);

Future<void> dbEnqueueCatalogScrape({
  required String assetKey,
  required String bookKey,
  required String sourceId,
  required String path,
  required String inputRevision,
  required String ruleVersion,
  required String trigger,
}) => RustLib.instance.api.crateApiScraperDbEnqueueCatalogScrape(
  assetKey: assetKey,
  bookKey: bookKey,
  sourceId: sourceId,
  path: path,
  inputRevision: inputRevision,
  ruleVersion: ruleVersion,
  trigger: trigger,
);

Future<ScrapeQueueDto?> dbClaimCatalogScrape({required PlatformInt64 now}) =>
    RustLib.instance.api.crateApiScraperDbClaimCatalogScrape(now: now);

Future<void> dbCompleteCatalogScrape({
  required PlatformInt64 id,
  required String status,
  String? lastError,
  required PlatformInt64 nextRunAt,
}) => RustLib.instance.api.crateApiScraperDbCompleteCatalogScrape(
  id: id,
  status: status,
  lastError: lastError,
  nextRunAt: nextRunAt,
);

Future<MaterializeResult> dbMaterializeReadyProposal({
  required String assetKey,
  required String expectedRevision,
}) => RustLib.instance.api.crateApiScraperDbMaterializeReadyProposal(
  assetKey: assetKey,
  expectedRevision: expectedRevision,
);

class ScrapeProposalDto {
  final String assetKey;
  final String bookKey;
  final String sourceId;
  final String path;
  final String filename;
  final String? title;
  final String authorsJson;
  final String? provider;
  final String? volume;
  final String? chapter;
  final String state;
  final String evidenceJson;
  final String conflictsJson;
  final String semanticJson;
  final String ruleVersion;
  final String inputRevision;
  final String materializationStatus;
  final String materializationError;
  final PlatformInt64? materializedAt;
  final String materializationAppliedFieldsJson;
  final String materializationAddedTagsJson;
  final String materializationSkippedFieldsJson;
  final PlatformInt64 updatedAt;

  const ScrapeProposalDto({
    required this.assetKey,
    required this.bookKey,
    required this.sourceId,
    required this.path,
    required this.filename,
    this.title,
    required this.authorsJson,
    this.provider,
    this.volume,
    this.chapter,
    required this.state,
    required this.evidenceJson,
    required this.conflictsJson,
    required this.semanticJson,
    required this.ruleVersion,
    required this.inputRevision,
    required this.materializationStatus,
    required this.materializationError,
    this.materializedAt,
    required this.materializationAppliedFieldsJson,
    required this.materializationAddedTagsJson,
    required this.materializationSkippedFieldsJson,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      assetKey.hashCode ^
      bookKey.hashCode ^
      sourceId.hashCode ^
      path.hashCode ^
      filename.hashCode ^
      title.hashCode ^
      authorsJson.hashCode ^
      provider.hashCode ^
      volume.hashCode ^
      chapter.hashCode ^
      state.hashCode ^
      evidenceJson.hashCode ^
      conflictsJson.hashCode ^
      semanticJson.hashCode ^
      ruleVersion.hashCode ^
      inputRevision.hashCode ^
      materializationStatus.hashCode ^
      materializationError.hashCode ^
      materializedAt.hashCode ^
      materializationAppliedFieldsJson.hashCode ^
      materializationAddedTagsJson.hashCode ^
      materializationSkippedFieldsJson.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScrapeProposalDto &&
          runtimeType == other.runtimeType &&
          assetKey == other.assetKey &&
          bookKey == other.bookKey &&
          sourceId == other.sourceId &&
          path == other.path &&
          filename == other.filename &&
          title == other.title &&
          authorsJson == other.authorsJson &&
          provider == other.provider &&
          volume == other.volume &&
          chapter == other.chapter &&
          state == other.state &&
          evidenceJson == other.evidenceJson &&
          conflictsJson == other.conflictsJson &&
          semanticJson == other.semanticJson &&
          ruleVersion == other.ruleVersion &&
          inputRevision == other.inputRevision &&
          materializationStatus == other.materializationStatus &&
          materializationError == other.materializationError &&
          materializedAt == other.materializedAt &&
          materializationAppliedFieldsJson ==
              other.materializationAppliedFieldsJson &&
          materializationAddedTagsJson == other.materializationAddedTagsJson &&
          materializationSkippedFieldsJson ==
              other.materializationSkippedFieldsJson &&
          updatedAt == other.updatedAt;
}

class ScrapeQueueDto {
  final PlatformInt64 id;
  final String assetKey;
  final String bookKey;
  final String sourceId;
  final String path;
  final String inputRevision;
  final String ruleVersion;
  final String trigger;
  final String status;
  final PlatformInt64 attempt;
  final PlatformInt64 nextRunAt;
  final String? lastError;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;

  const ScrapeQueueDto({
    required this.id,
    required this.assetKey,
    required this.bookKey,
    required this.sourceId,
    required this.path,
    required this.inputRevision,
    required this.ruleVersion,
    required this.trigger,
    required this.status,
    required this.attempt,
    required this.nextRunAt,
    this.lastError,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      assetKey.hashCode ^
      bookKey.hashCode ^
      sourceId.hashCode ^
      path.hashCode ^
      inputRevision.hashCode ^
      ruleVersion.hashCode ^
      trigger.hashCode ^
      status.hashCode ^
      attempt.hashCode ^
      nextRunAt.hashCode ^
      lastError.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScrapeQueueDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          assetKey == other.assetKey &&
          bookKey == other.bookKey &&
          sourceId == other.sourceId &&
          path == other.path &&
          inputRevision == other.inputRevision &&
          ruleVersion == other.ruleVersion &&
          trigger == other.trigger &&
          status == other.status &&
          attempt == other.attempt &&
          nextRunAt == other.nextRunAt &&
          lastError == other.lastError &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

class ScrapeRunDto {
  final String id;
  final String trigger;
  final String status;
  final String ruleVersion;
  final PlatformInt64 total;
  final PlatformInt64 processed;
  final PlatformInt64 ready;
  final PlatformInt64 ambiguous;
  final PlatformInt64 partial;
  final PlatformInt64 unmatched;
  final PlatformInt64 inputAssets;
  final PlatformInt64 uniqueAssets;
  final PlatformInt64 proposalsWritten;
  final PlatformInt64 assetCollisionCount;
  final PlatformInt64 bookGroupCollisionCount;
  final String accountingStatus;
  final String error;
  final PlatformInt64 requestedAt;
  final PlatformInt64? startedAt;
  final PlatformInt64? finishedAt;
  final PlatformInt64 updatedAt;

  const ScrapeRunDto({
    required this.id,
    required this.trigger,
    required this.status,
    required this.ruleVersion,
    required this.total,
    required this.processed,
    required this.ready,
    required this.ambiguous,
    required this.partial,
    required this.unmatched,
    required this.inputAssets,
    required this.uniqueAssets,
    required this.proposalsWritten,
    required this.assetCollisionCount,
    required this.bookGroupCollisionCount,
    required this.accountingStatus,
    required this.error,
    required this.requestedAt,
    this.startedAt,
    this.finishedAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      trigger.hashCode ^
      status.hashCode ^
      ruleVersion.hashCode ^
      total.hashCode ^
      processed.hashCode ^
      ready.hashCode ^
      ambiguous.hashCode ^
      partial.hashCode ^
      unmatched.hashCode ^
      inputAssets.hashCode ^
      uniqueAssets.hashCode ^
      proposalsWritten.hashCode ^
      assetCollisionCount.hashCode ^
      bookGroupCollisionCount.hashCode ^
      accountingStatus.hashCode ^
      error.hashCode ^
      requestedAt.hashCode ^
      startedAt.hashCode ^
      finishedAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScrapeRunDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          trigger == other.trigger &&
          status == other.status &&
          ruleVersion == other.ruleVersion &&
          total == other.total &&
          processed == other.processed &&
          ready == other.ready &&
          ambiguous == other.ambiguous &&
          partial == other.partial &&
          unmatched == other.unmatched &&
          inputAssets == other.inputAssets &&
          uniqueAssets == other.uniqueAssets &&
          proposalsWritten == other.proposalsWritten &&
          assetCollisionCount == other.assetCollisionCount &&
          bookGroupCollisionCount == other.bookGroupCollisionCount &&
          accountingStatus == other.accountingStatus &&
          error == other.error &&
          requestedAt == other.requestedAt &&
          startedAt == other.startedAt &&
          finishedAt == other.finishedAt &&
          updatedAt == other.updatedAt;
}
