// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'book.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `baidu_downloads`, `baidu_sessions`, `cloud115_downloads`, `cloud115_sessions`, `downloads`, `get_baidu_session`, `get_cloud115_session`, `get_quark_session`, `get_session`, `get_sftp_session`, `next_id`, `parse_strategy`, `quark_downloads`, `quark_sessions`, `sessions`, `sftp_downloads`, `sftp_sessions`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `OpenStrategy`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`

/// 连接 WebDAV 服务器并自动探测能力,返回会话句柄与初始浏览路径。
Future<WebDavSession> webdavConnect({
  required String url,
  required String username,
  required String password,
}) => RustLib.instance.api.crateApiSourceWebdavConnect(
  url: url,
  username: username,
  password: password,
);

/// 断开 WebDAV 会话。在 blocking 线程销毁客户端,避免异步上下文 drop 其内部 runtime。
Future<void> webdavDisconnect({required BigInt id}) =>
    RustLib.instance.api.crateApiSourceWebdavDisconnect(id: id);

/// 列出 WebDAV 目录内容(目录在前,自然排序)。
Future<List<DirEntry>> webdavList({
  required BigInt session,
  required String path,
}) =>
    RustLib.instance.api.crateApiSourceWebdavList(session: session, path: path);

/// 打开 WebDAV 上的书籍。
/// 策略(strategy): "auto" 先尝试整本下载到 raw/ 缓存, 失败回退流式;
/// "download" 强制整本下载(失败报错); "stream" 直接流式(无 Range 服务器仍需整本)。
/// 若已有缓存则直接复用(秒开)。
/// 这是四层架构的关键: 阅读器只操作本地资源。
/// 下载进度可通过 webdav_download_progress(session) 轮询。
Future<BookInfo> openWebdavBook({
  required BigInt session,
  required String path,
  required String strategy,
}) => RustLib.instance.api.crateApiSourceOpenWebdavBook(
  session: session,
  path: path,
  strategy: strategy,
);

/// 查询当前下载进度(0.0 ~ 1.0),若 session 不在下载中则返回 1.0。
Future<double> webdavDownloadProgress({required BigInt session}) =>
    RustLib.instance.api.crateApiSourceWebdavDownloadProgress(session: session);

/// 检查某 WebDAV 漫画是否已有 raw/ 本地缓存。
Future<bool> webdavHasRawCache({
  required BigInt session,
  required String path,
}) => RustLib.instance.api.crateApiSourceWebdavHasRawCache(
  session: session,
  path: path,
);

/// 连接 SFTP 服务器（密码认证），返回会话句柄；root 固定为 `/`。
Future<SftpSessionInfo> sftpConnect({
  required String host,
  required int port,
  required String username,
  required String password,
}) => RustLib.instance.api.crateApiSourceSftpConnect(
  host: host,
  port: port,
  username: username,
  password: password,
);

/// 断开 SFTP 会话（在 blocking 线程释放连接与 runtime）。
Future<void> sftpDisconnect({required BigInt id}) =>
    RustLib.instance.api.crateApiSourceSftpDisconnect(id: id);

/// 列出 SFTP 目录内容（目录在前,自然排序）。
Future<List<DirEntry>> sftpList({
  required BigInt session,
  required String path,
}) => RustLib.instance.api.crateApiSourceSftpList(session: session, path: path);

/// 打开 SFTP 上的书籍，strategy 见 [`open_webdav_book`]。
/// 整本下载优先（进度经 sftp_download_progress 轮询）；失败回退 SftpFile 流式。
Future<BookInfo> openSftpBook({
  required BigInt session,
  required String path,
  required String strategy,
}) => RustLib.instance.api.crateApiSourceOpenSftpBook(
  session: session,
  path: path,
  strategy: strategy,
);

/// 查询 SFTP 下载进度（0.0 ~ 1.0），非下载中返回 1.0。
Future<double> sftpDownloadProgress({required BigInt session}) =>
    RustLib.instance.api.crateApiSourceSftpDownloadProgress(session: session);

/// 检查某 SFTP 漫画是否已有 raw/ 本地缓存。
Future<bool> sftpHasRawCache({required BigInt session, required String path}) =>
    RustLib.instance.api.crateApiSourceSftpHasRawCache(
      session: session,
      path: path,
    );

/// 生成 SFTP 书籍封面缩略图（优先 cover/ 磁盘缓存 → raw/ 本地缓存 → 流式解码）。
Future<PageImage> sftpCover({
  required BigInt session,
  required String path,
  required int page,
  required int width,
  required int height,
  CropRect? crop,
}) => RustLib.instance.api.crateApiSourceSftpCover(
  session: session,
  path: path,
  page: page,
  width: width,
  height: height,
  crop: crop,
);

/// 连接夸克网盘：`/config` + 根目录连通性测试，返回会话。
Future<QuarkSessionInfo> quarkConnect({
  required String cookie,
  required String rootId,
}) => RustLib.instance.api.crateApiSourceQuarkConnect(
  cookie: cookie,
  rootId: rootId,
);

/// 断开夸克会话。
Future<void> quarkDisconnect({required BigInt id}) =>
    RustLib.instance.api.crateApiSourceQuarkDisconnect(id: id);

/// 列出夸克目录（path 为文件夹 fid，根目录 `0`）。
Future<List<DirEntry>> quarkList({
  required BigInt session,
  required String path,
}) =>
    RustLib.instance.api.crateApiSourceQuarkList(session: session, path: path);

/// 打开夸克网盘上的书籍（path 为文件 fid，三态策略；格式探测走真实文件名）。
Future<BookInfo> openQuarkBook({
  required BigInt session,
  required String path,
  required String strategy,
}) => RustLib.instance.api.crateApiSourceOpenQuarkBook(
  session: session,
  path: path,
  strategy: strategy,
);

/// 夸克下载进度（0.0~1.0，非下载中返回 1.0）。
Future<double> quarkDownloadProgress({required BigInt session}) =>
    RustLib.instance.api.crateApiSourceQuarkDownloadProgress(session: session);

/// 夸克书籍是否已有 raw/ 本地缓存。
Future<bool> quarkHasRawCache({
  required BigInt session,
  required String path,
}) => RustLib.instance.api.crateApiSourceQuarkHasRawCache(
  session: session,
  path: path,
);

/// 夸克书籍封面（cover/ 磁盘缓存 → raw/ 本地缓存 → 流式解码）。
Future<PageImage> quarkCover({
  required BigInt session,
  required String path,
  required int page,
  required int width,
  required int height,
  CropRect? crop,
}) => RustLib.instance.api.crateApiSourceQuarkCover(
  session: session,
  path: path,
  page: page,
  width: width,
  height: height,
  crop: crop,
);

/// 生成 WebDAV 书籍封面缩略图(取第 page 页,等比缩放 + 中心裁剪到 w×h)。
/// 封面结果写入磁盘缓存（cover/）供后续秒开。
/// 优先走磁盘缓存 → raw/ 本地缓存 → HTTP Range 流式。
Future<PageImage> webdavCover({
  required BigInt session,
  required String path,
  required int page,
  required int width,
  required int height,
  CropRect? crop,
}) => RustLib.instance.api.crateApiSourceWebdavCover(
  session: session,
  path: path,
  page: page,
  width: width,
  height: height,
  crop: crop,
);

/// 构造百度 OAuth 授权链接（浏览器打开，redirect_uri=oob）。
Future<String> baiduAuthUrl({required String appKey}) =>
    RustLib.instance.api.crateApiSourceBaiduAuthUrl(appKey: appKey);

/// 授权码换 token（不建会话）。
Future<BaiduTokenPair> baiduExchangeCode({
  required String appKey,
  required String clientSecret,
  required String code,
}) => RustLib.instance.api.crateApiSourceBaiduExchangeCode(
  appKey: appKey,
  clientSecret: clientSecret,
  code: code,
);

/// 连接百度网盘：刷新/校验 token + 连通性测试，返回会话与最新 refresh_token。
Future<BaiduSessionInfo> baiduConnect({
  required String refreshToken,
  required String appKey,
  required String clientSecret,
  required String root,
}) => RustLib.instance.api.crateApiSourceBaiduConnect(
  refreshToken: refreshToken,
  appKey: appKey,
  clientSecret: clientSecret,
  root: root,
);

/// 断开百度会话。
Future<void> baiduDisconnect({required BigInt id}) =>
    RustLib.instance.api.crateApiSourceBaiduDisconnect(id: id);

/// 列出百度网盘目录（按路径）。
Future<List<DirEntry>> baiduList({
  required BigInt session,
  required String path,
}) =>
    RustLib.instance.api.crateApiSourceBaiduList(session: session, path: path);

/// 打开百度网盘上的书籍（三态策略，镜像 open_webdav_book）。
Future<BookInfo> openBaiduBook({
  required BigInt session,
  required String path,
  required String strategy,
}) => RustLib.instance.api.crateApiSourceOpenBaiduBook(
  session: session,
  path: path,
  strategy: strategy,
);

/// 百度下载进度（0.0~1.0，非下载中返回 1.0）。
Future<double> baiduDownloadProgress({required BigInt session}) =>
    RustLib.instance.api.crateApiSourceBaiduDownloadProgress(session: session);

/// 百度书籍是否已有 raw/ 本地缓存。
Future<bool> baiduHasRawCache({
  required BigInt session,
  required String path,
}) => RustLib.instance.api.crateApiSourceBaiduHasRawCache(
  session: session,
  path: path,
);

/// 百度书籍封面（cover/ 磁盘缓存 → raw/ 本地缓存 → 流式解码）。
Future<PageImage> baiduCover({
  required BigInt session,
  required String path,
  required int page,
  required int width,
  required int height,
  CropRect? crop,
}) => RustLib.instance.api.crateApiSourceBaiduCover(
  session: session,
  path: path,
  page: page,
  width: width,
  height: height,
  crop: crop,
);

/// 开始 115 设备码授权（Dart 渲染二维码）。
Future<Cloud115QrPayload> cloud115QrStart({required String appId}) =>
    RustLib.instance.api.crateApiSourceCloud115QrStart(appId: appId);

/// 轮询 115 扫码状态；status=2 返回 token。
Future<Cloud115QrPollResult> cloud115QrPoll({
  required String uid,
  required PlatformInt64 time,
  required String sign,
}) => RustLib.instance.api.crateApiSourceCloud115QrPoll(
  uid: uid,
  time: time,
  sign: sign,
);

/// 连接 115 网盘：刷新/校验 token + 连通性测试，返回会话与最新 refresh_token。
Future<Cloud115SessionInfo> cloud115Connect({
  required String refreshToken,
  required String appId,
  required String rootId,
}) => RustLib.instance.api.crateApiSourceCloud115Connect(
  refreshToken: refreshToken,
  appId: appId,
  rootId: rootId,
);

/// 断开 115 会话。
Future<void> cloud115Disconnect({required BigInt id}) =>
    RustLib.instance.api.crateApiSourceCloud115Disconnect(id: id);

/// 列出 115 目录（path 为文件夹 ID）。
Future<List<DirEntry>> cloud115List({
  required BigInt session,
  required String path,
}) => RustLib.instance.api.crateApiSourceCloud115List(
  session: session,
  path: path,
);

/// 打开 115 上的书籍（path 为文件提取码，三态策略）。
Future<BookInfo> openCloud115Book({
  required BigInt session,
  required String path,
  required String strategy,
}) => RustLib.instance.api.crateApiSourceOpenCloud115Book(
  session: session,
  path: path,
  strategy: strategy,
);

/// 115 下载进度（0.0~1.0，非下载中返回 1.0）。
Future<double> cloud115DownloadProgress({required BigInt session}) => RustLib
    .instance
    .api
    .crateApiSourceCloud115DownloadProgress(session: session);

/// 115 书籍是否已有 raw/ 本地缓存。
Future<bool> cloud115HasRawCache({
  required BigInt session,
  required String path,
}) => RustLib.instance.api.crateApiSourceCloud115HasRawCache(
  session: session,
  path: path,
);

/// 115 书籍封面（cover/ 磁盘缓存 → raw/ 本地缓存 → 流式解码）。
Future<PageImage> cloud115Cover({
  required BigInt session,
  required String path,
  required int page,
  required int width,
  required int height,
  CropRect? crop,
}) => RustLib.instance.api.crateApiSourceCloud115Cover(
  session: session,
  path: path,
  page: page,
  width: width,
  height: height,
  crop: crop,
);

/// 百度会话信息。
class BaiduSessionInfo {
  final BigInt id;
  final String root;
  final String capabilityLabel;

  /// 刷新后的 refresh_token（Dart 回写 DB）。
  final String refreshToken;

  const BaiduSessionInfo({
    required this.id,
    required this.root,
    required this.capabilityLabel,
    required this.refreshToken,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      root.hashCode ^
      capabilityLabel.hashCode ^
      refreshToken.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BaiduSessionInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          root == other.root &&
          capabilityLabel == other.capabilityLabel &&
          refreshToken == other.refreshToken;
}

/// 百度 token 对（授权码换 token / 刷新结果）。
class BaiduTokenPair {
  final String accessToken;
  final String refreshToken;

  const BaiduTokenPair({required this.accessToken, required this.refreshToken});

  @override
  int get hashCode => accessToken.hashCode ^ refreshToken.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BaiduTokenPair &&
          runtimeType == other.runtimeType &&
          accessToken == other.accessToken &&
          refreshToken == other.refreshToken;
}

/// 115 扫码授权二维码载荷。
class Cloud115QrPayload {
  final String uid;
  final PlatformInt64 time;
  final String sign;
  final String qrcode;

  const Cloud115QrPayload({
    required this.uid,
    required this.time,
    required this.sign,
    required this.qrcode,
  });

  @override
  int get hashCode =>
      uid.hashCode ^ time.hashCode ^ sign.hashCode ^ qrcode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Cloud115QrPayload &&
          runtimeType == other.runtimeType &&
          uid == other.uid &&
          time == other.time &&
          sign == other.sign &&
          qrcode == other.qrcode;
}

/// 115 扫码轮询结果。
class Cloud115QrPollResult {
  final int status;
  final String? accessToken;
  final String? refreshToken;

  const Cloud115QrPollResult({
    required this.status,
    this.accessToken,
    this.refreshToken,
  });

  @override
  int get hashCode =>
      status.hashCode ^ accessToken.hashCode ^ refreshToken.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Cloud115QrPollResult &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          accessToken == other.accessToken &&
          refreshToken == other.refreshToken;
}

/// 115 会话信息。
class Cloud115SessionInfo {
  final BigInt id;
  final String root;
  final String capabilityLabel;

  /// 刷新后的 refresh_token（Dart 回写 DB）。
  final String refreshToken;

  const Cloud115SessionInfo({
    required this.id,
    required this.root,
    required this.capabilityLabel,
    required this.refreshToken,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      root.hashCode ^
      capabilityLabel.hashCode ^
      refreshToken.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Cloud115SessionInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          root == other.root &&
          capabilityLabel == other.capabilityLabel &&
          refreshToken == other.refreshToken;
}

/// 夸克网盘会话信息。
class QuarkSessionInfo {
  final BigInt id;
  final String root;

  /// "quark"
  final String capabilityLabel;

  /// 会话内可能回写了 `__puus` 等续期 cookie；Dart 侧与 DB 不一致时回写。
  final String cookie;

  const QuarkSessionInfo({
    required this.id,
    required this.root,
    required this.capabilityLabel,
    required this.cookie,
  });

  @override
  int get hashCode =>
      id.hashCode ^ root.hashCode ^ capabilityLabel.hashCode ^ cookie.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QuarkSessionInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          root == other.root &&
          capabilityLabel == other.capabilityLabel &&
          cookie == other.cookie;
}

/// SFTP 会话信息。
class SftpSessionInfo {
  final BigInt id;
  final String root;

  /// 能力标记（Dart 侧显示用）。
  final String capabilityLabel;

  const SftpSessionInfo({
    required this.id,
    required this.root,
    required this.capabilityLabel,
  });

  @override
  int get hashCode => id.hashCode ^ root.hashCode ^ capabilityLabel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SftpSessionInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          root == other.root &&
          capabilityLabel == other.capabilityLabel;
}

/// WebDAV 会话信息。
class WebDavSession {
  final BigInt id;
  final String root;

  /// 服务器能力报告摘要(Dart 侧用于显示状态标记)。
  final String capabilityLabel;

  const WebDavSession({
    required this.id,
    required this.root,
    required this.capabilityLabel,
  });

  @override
  int get hashCode => id.hashCode ^ root.hashCode ^ capabilityLabel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WebDavSession &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          root == other.root &&
          capabilityLabel == other.capabilityLabel;
}
