// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'book.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `downloads`, `get_session`, `next_id`, `sessions`

/// 连接 WebDAV 服务器并自动探测能力,返回会话句柄与初始浏览路径。
Future<WebDavSession> webdavConnect({
  required String url,
  required String username,
  required String password,
}) => RustLib.instance.api.crateApiSourceWebdavConnect(
  url: url,
  username: username,
  password: password,
);

/// 断开 WebDAV 会话。在 blocking 线程销毁客户端,避免异步上下文 drop 其内部 runtime。
Future<void> webdavDisconnect({required BigInt id}) =>
    RustLib.instance.api.crateApiSourceWebdavDisconnect(id: id);

/// 列出 WebDAV 目录内容(目录在前,自然排序)。
Future<List<DirEntry>> webdavList({
  required BigInt session,
  required String path,
}) =>
    RustLib.instance.api.crateApiSourceWebdavList(session: session, path: path);

/// 打开 WebDAV 上的书籍。
/// 策略: 先尝试整本下载到 raw/ 缓存, 后续基于本地缓存阅读。
/// 若已有缓存则直接复用(秒开)。
/// 这是四层架构的关键: 阅读器只操作本地资源。
/// 下载进度可通过 webdav_download_progress(session) 轮询。
Future<BookInfo> openWebdavBook({
  required BigInt session,
  required String path,
}) => RustLib.instance.api.crateApiSourceOpenWebdavBook(
  session: session,
  path: path,
);

/// 查询当前下载进度(0.0 ~ 1.0),若 session 不在下载中则返回 1.0。
Future<double> webdavDownloadProgress({required BigInt session}) =>
    RustLib.instance.api.crateApiSourceWebdavDownloadProgress(session: session);

/// 检查某 WebDAV 漫画是否已有 raw/ 本地缓存。
Future<bool> webdavHasRawCache({
  required BigInt session,
  required String path,
}) => RustLib.instance.api.crateApiSourceWebdavHasRawCache(
  session: session,
  path: path,
);

/// 生成 WebDAV 书籍封面缩略图(取第 page 页,等比缩放 + 中心裁剪到 w×h)。
/// 封面结果写入磁盘缓存（cover/）供后续秒开。
/// 优先走磁盘缓存 → raw/ 本地缓存 → HTTP Range 流式。
Future<PageImage> webdavCover({
  required BigInt session,
  required String path,
  required int page,
  required int width,
  required int height,
  CropRect? crop,
}) => RustLib.instance.api.crateApiSourceWebdavCover(
  session: session,
  path: path,
  page: page,
  width: width,
  height: height,
  crop: crop,
);

/// WebDAV 会话信息。
class WebDavSession {
  final BigInt id;
  final String root;

  /// 服务器能力报告摘要(Dart 侧用于显示状态标记)。
  final String capabilityLabel;

  const WebDavSession({
    required this.id,
    required this.root,
    required this.capabilityLabel,
  });

  @override
  int get hashCode => id.hashCode ^ root.hashCode ^ capabilityLabel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WebDavSession &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          root == other.root &&
          capabilityLabel == other.capabilityLabel;
}
