// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `outcome_to_dto`

/// 执行一次完整同步（WebDAV session + 同步目录 + 本机平台标识）。
Future<SyncOutcomeDto> syncNow({
  required BigInt session,
  required String dir,
  required String platform,
}) => RustLib.instance.api.crateApiSyncSyncNow(
  session: session,
  dir: dir,
  platform: platform,
);

/// 轻量轮询：只读远端 manifest revision（无 manifest → 0）。
/// ADR-028 §12.6：定时轮询先比较 revision，未变化则不触发全量同步
/// （避免每 60 秒全量下载状态文件 + 写历史，坚果云被打到 503 的根因之一）。
Future<PlatformInt64> syncRemoteRevision({
  required BigInt session,
  required String dir,
}) => RustLib.instance.api.crateApiSyncSyncRemoteRevision(
  session: session,
  dir: dir,
);

/// 读取同步状态。
Future<SyncStatusDto> syncStatus() =>
    RustLib.instance.api.crateApiSyncSyncStatus();

/// 记录最近一次同步错误（设置页展示）。
Future<void> syncSetLastError({required String message}) =>
    RustLib.instance.api.crateApiSyncSyncSetLastError(message: message);

/// 清除同步错误标记。
Future<void> syncClearLastError() =>
    RustLib.instance.api.crateApiSyncSyncClearLastError();

/// 供诊断/调试：各实体本地快照规模。
Future<Map<String, PlatformInt64>> syncLocalCounts() =>
    RustLib.instance.api.crateApiSyncSyncLocalCounts();

/// 最近 N 条同步历史（倒序）。
Future<List<SyncHistoryDto>> syncHistoryRecent({
  required PlatformInt64 limit,
}) => RustLib.instance.api.crateApiSyncSyncHistoryRecent(limit: limit);

Future<List<SyncDeviceDto>> syncDevicesList() =>
    RustLib.instance.api.crateApiSyncSyncDevicesList();

/// 各实体合并变化数。
class EntityCountDto {
  final String entity;
  final PlatformInt64 count;

  const EntityCountDto({required this.entity, required this.count});

  @override
  int get hashCode => entity.hashCode ^ count.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EntityCountDto &&
          runtimeType == other.runtimeType &&
          entity == other.entity &&
          count == other.count;
}

/// 同步参与者列表（Phase 6 设备分组 UI 用）。
class SyncDeviceDto {
  final String deviceId;
  final String deviceName;
  final String platform;
  final PlatformInt64 lastSeenAt;
  final PlatformInt64 lastRevision;

  const SyncDeviceDto({
    required this.deviceId,
    required this.deviceName,
    required this.platform,
    required this.lastSeenAt,
    required this.lastRevision,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      deviceName.hashCode ^
      platform.hashCode ^
      lastSeenAt.hashCode ^
      lastRevision.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncDeviceDto &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          deviceName == other.deviceName &&
          platform == other.platform &&
          lastSeenAt == other.lastSeenAt &&
          lastRevision == other.lastRevision;
}

/// 同步历史条目（可观测性）。
class SyncHistoryDto {
  final PlatformInt64 id;
  final PlatformInt64 startTime;
  final PlatformInt64 endTime;
  final PlatformInt64 revisionBefore;
  final PlatformInt64 revisionAfter;
  final PlatformInt64 pullCount;
  final PlatformInt64 pushCount;
  final PlatformInt64 mergeCount;
  final PlatformInt64 conflictCount;
  final String error;
  final String summary;

  const SyncHistoryDto({
    required this.id,
    required this.startTime,
    required this.endTime,
    required this.revisionBefore,
    required this.revisionAfter,
    required this.pullCount,
    required this.pushCount,
    required this.mergeCount,
    required this.conflictCount,
    required this.error,
    required this.summary,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      startTime.hashCode ^
      endTime.hashCode ^
      revisionBefore.hashCode ^
      revisionAfter.hashCode ^
      pullCount.hashCode ^
      pushCount.hashCode ^
      mergeCount.hashCode ^
      conflictCount.hashCode ^
      error.hashCode ^
      summary.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncHistoryDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          startTime == other.startTime &&
          endTime == other.endTime &&
          revisionBefore == other.revisionBefore &&
          revisionAfter == other.revisionAfter &&
          pullCount == other.pullCount &&
          pushCount == other.pushCount &&
          mergeCount == other.mergeCount &&
          conflictCount == other.conflictCount &&
          error == other.error &&
          summary == other.summary;
}

/// 一次同步结果。
class SyncOutcomeDto {
  final bool initialized;
  final PlatformInt64 revision;
  final List<EntityCountDto> changedEntities;
  final PlatformInt64 pullCount;
  final PlatformInt64 pushCount;
  final PlatformInt64 mergeCount;
  final PlatformInt64 deletedCount;

  /// Sync Plan 的 JSON 文本（debug/诊断；正常流程不解析）。
  final String planJson;

  const SyncOutcomeDto({
    required this.initialized,
    required this.revision,
    required this.changedEntities,
    required this.pullCount,
    required this.pushCount,
    required this.mergeCount,
    required this.deletedCount,
    required this.planJson,
  });

  @override
  int get hashCode =>
      initialized.hashCode ^
      revision.hashCode ^
      changedEntities.hashCode ^
      pullCount.hashCode ^
      pushCount.hashCode ^
      mergeCount.hashCode ^
      deletedCount.hashCode ^
      planJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncOutcomeDto &&
          runtimeType == other.runtimeType &&
          initialized == other.initialized &&
          revision == other.revision &&
          changedEntities == other.changedEntities &&
          pullCount == other.pullCount &&
          pushCount == other.pushCount &&
          mergeCount == other.mergeCount &&
          deletedCount == other.deletedCount &&
          planJson == other.planJson;
}

/// 同步状态（设置页展示）。
class SyncStatusDto {
  final bool initialized;
  final PlatformInt64 revision;
  final PlatformInt64 lastSyncAt;
  final String lastError;
  final String libraryId;

  const SyncStatusDto({
    required this.initialized,
    required this.revision,
    required this.lastSyncAt,
    required this.lastError,
    required this.libraryId,
  });

  @override
  int get hashCode =>
      initialized.hashCode ^
      revision.hashCode ^
      lastSyncAt.hashCode ^
      lastError.hashCode ^
      libraryId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncStatusDto &&
          runtimeType == other.runtimeType &&
          initialized == other.initialized &&
          revision == other.revision &&
          lastSyncAt == other.lastSyncAt &&
          lastError == other.lastError &&
          libraryId == other.libraryId;
}
