use super::model::{RemoteEntry, RemoteScanState};
use rusqlite::{params, Connection, Result};

pub fn migrate(conn: &Connection) -> Result<()> {
    for (n,t) in [("asset_kind","TEXT"),("content_fingerprint","TEXT"),("scan_generation","INTEGER"),("listing_complete","INTEGER NOT NULL DEFAULT 0")] { let _=conn.execute(&format!("ALTER TABLE library_index ADD COLUMN {n} {t}"),[]); }
    conn.execute_batch("CREATE TABLE IF NOT EXISTS remote_scan_state (source_id TEXT PRIMARY KEY,status TEXT NOT NULL,mode TEXT NOT NULL,generation INTEGER NOT NULL,checkpoint TEXT,last_success_at INTEGER,error_code TEXT); CREATE TABLE IF NOT EXISTS remote_listing_state (source_id TEXT NOT NULL,logical_path TEXT NOT NULL,content_fingerprint TEXT,scan_generation INTEGER NOT NULL,listing_complete INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(source_id,logical_path)); CREATE TABLE IF NOT EXISTS remote_cover_dependency (book_key TEXT NOT NULL,dependency_path TEXT NOT NULL,dependency_fingerprint TEXT NOT NULL,profile TEXT NOT NULL,status TEXT NOT NULL,PRIMARY KEY(book_key,dependency_path)); CREATE INDEX IF NOT EXISTS idx_remote_listing_source_path ON remote_listing_state(source_id,logical_path); CREATE INDEX IF NOT EXISTS idx_remote_cover_book_path ON remote_cover_dependency(book_key,dependency_path);")
}
pub fn load_checkpoint(conn:&Connection, source_id:&str)->Result<Option<String>> { conn.query_row("SELECT checkpoint FROM remote_scan_state WHERE source_id=?1",[source_id],|r|r.get(0)).or_else(|e| if matches!(e,rusqlite::Error::QueryReturnedNoRows){Ok(None)}else{Err(e)}) }
pub fn mark_scan_status(conn:&Connection,state:&RemoteScanState)->Result<()> { conn.execute("INSERT INTO remote_scan_state(source_id,status,mode,generation,checkpoint,last_success_at,error_code) VALUES(?1,?2,?3,?4,?5,?6,?7) ON CONFLICT(source_id) DO UPDATE SET status=excluded.status,mode=excluded.mode,generation=excluded.generation,checkpoint=excluded.checkpoint,last_success_at=excluded.last_success_at,error_code=excluded.error_code",params![state.source_id,format!("{:?}",state.status),format!("{:?}",state.mode),state.generation,state.checkpoint,state.last_success_at,state.error_code])?; Ok(()) }
pub fn upsert_complete_listing(conn:&Connection,source_id:&str,path:&str,entries:&[RemoteEntry],generation:i64,fingerprint:&str,complete:bool)->Result<()> { let tx=conn.unchecked_transaction()?; for e in entries { tx.execute("UPDATE library_index SET asset_kind=?1,content_fingerprint=?2,scan_generation=?3,listing_complete=?4,size=?5,modified_at=?6,deleted=0 WHERE source_id=?7 AND path=?8",params![format!("{:?}",e.asset_kind),fingerprint,generation,complete as i64,e.size.map(|v|v as i64),e.mtime,source_id,e.logical_path])?; } tx.execute("INSERT INTO remote_listing_state VALUES(?1,?2,?3,?4,?5) ON CONFLICT(source_id,logical_path) DO UPDATE SET content_fingerprint=excluded.content_fingerprint,scan_generation=excluded.scan_generation,listing_complete=excluded.listing_complete",params![source_id,path,fingerprint,generation,complete as i64])?; tx.commit()
}
pub fn replace_verified_children(conn:&Connection,source_id:&str,parent:&str,paths:&[String],generation:i64)->Result<()> { let tx=conn.unchecked_transaction()?; for p in paths { tx.execute("UPDATE library_index SET deleted=0,scan_generation=?1 WHERE source_id=?2 AND path=?3",params![generation,source_id,p])?; } if !paths.is_empty() { tx.execute("UPDATE library_index SET deleted=1 WHERE source_id=?1 AND parent_id IS NOT NULL AND path LIKE ?2 AND scan_generation < ?3 AND listing_complete=1",params![source_id,format!("{parent}/%"),generation])?; } tx.commit() }
