use super::model::{RemoteEntry, RemoteScanState};
use rusqlite::{params, Connection, Result};

pub fn migrate(conn: &Connection) -> Result<()> {
    for (n,t) in [("asset_kind","TEXT"),("content_fingerprint","TEXT"),("scan_generation","INTEGER"),("listing_complete","INTEGER NOT NULL DEFAULT 0")] { let exists: bool=conn.query_row("SELECT EXISTS(SELECT 1 FROM pragma_table_info('library_index') WHERE name=?1)",[n],|r|r.get(0))?; if !exists { conn.execute(&format!("ALTER TABLE library_index ADD COLUMN {n} {t}"),[])?; } }
    conn.execute_batch("CREATE TABLE IF NOT EXISTS remote_scan_state (source_id TEXT PRIMARY KEY,status TEXT NOT NULL,mode TEXT NOT NULL,generation INTEGER NOT NULL,checkpoint TEXT,last_success_at INTEGER,error_code TEXT); CREATE TABLE IF NOT EXISTS remote_listing_state (source_id TEXT NOT NULL,logical_path TEXT NOT NULL,content_fingerprint TEXT,scan_generation INTEGER NOT NULL,listing_complete INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(source_id,logical_path)); CREATE TABLE IF NOT EXISTS remote_cover_dependency (book_key TEXT NOT NULL,dependency_path TEXT NOT NULL,dependency_fingerprint TEXT NOT NULL,profile TEXT NOT NULL,status TEXT NOT NULL,PRIMARY KEY(book_key,dependency_path)); CREATE INDEX IF NOT EXISTS idx_remote_listing_source_path ON remote_listing_state(source_id,logical_path); CREATE INDEX IF NOT EXISTS idx_remote_cover_book_path ON remote_cover_dependency(book_key,dependency_path);")
}
pub fn load_checkpoint(conn:&Connection, source_id:&str)->Result<Option<String>> { conn.query_row("SELECT checkpoint FROM remote_scan_state WHERE source_id=?1",[source_id],|r|r.get::<_,Option<String>>(0)).or_else(|e| if matches!(e,rusqlite::Error::QueryReturnedNoRows){Ok(None)}else{Err(e)}) }
pub fn mark_scan_status(conn:&Connection,state:&RemoteScanState)->Result<()> { conn.execute("INSERT INTO remote_scan_state(source_id,status,mode,generation,checkpoint,last_success_at,error_code) VALUES(?1,?2,?3,?4,?5,?6,?7) ON CONFLICT(source_id) DO UPDATE SET status=excluded.status,mode=excluded.mode,generation=excluded.generation,checkpoint=excluded.checkpoint,last_success_at=excluded.last_success_at,error_code=excluded.error_code",params![state.source_id,format!("{:?}",state.status),format!("{:?}",state.mode),state.generation,state.checkpoint,state.last_success_at,state.error_code])?; Ok(()) }
pub fn upsert_complete_listing(conn:&Connection,source_id:&str,path:&str,entries:&[RemoteEntry],generation:i64,fingerprint:&str,complete:bool)->Result<()> { let tx=conn.unchecked_transaction()?; let source_fp:String=tx.query_row("SELECT fingerprint FROM book_sources WHERE id=?1 AND fingerprint IS NOT NULL AND fingerprint <> ''",[source_id],|r|r.get(0))?; let now=crate::db::now_ms(); for e in entries { let id=crate::db::library_index_id(&source_fp,&e.logical_path); let parent=e.logical_path.rfind('/').map(|i| if i == 0 { "/" } else { &e.logical_path[..i] }); let parent_id=parent.map(|p|crate::db::library_index_id(&source_fp,p)); tx.execute("INSERT INTO library_index(id,source_id,parent_id,name,path,entry_type,size,modified_at,asset_kind,content_fingerprint,scan_generation,listing_complete,deleted,updated_at) VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11,?12,0,?13) ON CONFLICT(id) DO UPDATE SET parent_id=excluded.parent_id,name=excluded.name,size=excluded.size,modified_at=excluded.modified_at,asset_kind=excluded.asset_kind,content_fingerprint=excluded.content_fingerprint,scan_generation=excluded.scan_generation,listing_complete=excluded.listing_complete,deleted=0,updated_at=excluded.updated_at",params![id,source_id,parent_id,e.name,e.logical_path,if e.is_dir{"dir"}else{"file"},e.size.map(|v|v as i64),e.mtime,format!("{:?}",e.asset_kind),fingerprint,generation,complete as i64,now])?; } tx.execute("INSERT INTO remote_listing_state VALUES(?1,?2,?3,?4,?5) ON CONFLICT(source_id,logical_path) DO UPDATE SET content_fingerprint=excluded.content_fingerprint,scan_generation=excluded.scan_generation,listing_complete=excluded.listing_complete",params![source_id,path,fingerprint,generation,complete as i64])?; tx.commit()
}
pub fn replace_verified_children(conn:&Connection,source_id:&str,parent:&str,paths:&[String],generation:i64,complete:bool)->Result<()> { let tx=conn.unchecked_transaction()?; let now=crate::db::now_ms(); for p in paths { tx.execute("UPDATE library_index SET deleted=0,scan_generation=?1,updated_at=?4 WHERE source_id=?2 AND path=?3",params![generation,source_id,p,now])?; } let proven:bool=tx.query_row("SELECT EXISTS(SELECT 1 FROM remote_listing_state WHERE source_id=?1 AND logical_path=?2 AND scan_generation=?3 AND listing_complete=1)",[source_id, if parent.is_empty(){"/"}else{parent}, generation],|r|r.get(0))?; if complete && proven { let parent_path=if parent.is_empty(){"/"}else{parent}; tx.execute("UPDATE library_index SET deleted=1,updated_at=?4 WHERE source_id=?1 AND parent_id=COALESCE((SELECT id FROM library_index WHERE source_id=?1 AND path=?2), (SELECT id FROM library_index WHERE source_id=?1 AND path='/')) AND scan_generation < ?3 AND listing_complete=1",params![source_id,parent_path,generation,now])?; } tx.commit() }
